chapter \<open>Generated by Lem from \<open>pmp_extract_types.lem\<close>.\<close>

theory "Pmp_extract_types" 

imports
  Main
  "LEM.Lem_pervasives_extra"
  "Sail2_instr_kinds"
  "Sail2_values"
  "Sail2_string"
  "Sail2_operators_bitlists"
  "Sail2_prompt_monad"
  "Sail2_prompt"
  "Sail2_undefined"

begin 

\<comment> \<open>\<open>Generated by Sail: types and register state\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>
\<comment> \<open>\<open>open import Sail2_string\<close>\<close>
\<comment> \<open>\<open>open import Sail2_operators_bitlists\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt_monad\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt\<close>\<close>
\<comment> \<open>\<open>open import Sail2_undefined\<close>\<close>

type_synonym bit0  =" bitU list "


type_synonym bits  =" bitU list "




datatype pmpAddrMatch =   PMP_NoMatch | PMP_PartialMatch | PMP_Match



datatype register_value  =
    Regval_vector " ( register_value list)"
  | Regval_list " ( register_value list)"
  | Regval_option " ( register_value option)"
  | Regval_bool " (bool)"
  | Regval_int " (ii)"
  | Regval_real " (real)"
  | Regval_string " (string)"
  | Regval_bitvector_1 " ( bitU list)"



type_synonym regstate  =" unit "


\<comment> \<open>\<open>val bitvector_1_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_1_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_1_of_regval (Regval_bitvector_1 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_1_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_1 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_1  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_1 v0 = ( Regval_bitvector_1 v0 )\<close> 
  for  "v0"  :: "(bitU)list "




\<comment> \<open>\<open>val bool_of_register_value : register_value -> maybe bool\<close>\<close>
fun bool_of_register_value  :: \<open> register_value \<Rightarrow>(bool)option \<close>  where 
     \<open> bool_of_register_value (Regval_bool v) = ( Some v )\<close> 
  for  "v"  :: " bool "
|\<open> bool_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_bool : bool -> register_value\<close>\<close>
definition register_value_of_bool  :: \<open> bool \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_bool v = ( Regval_bool v )\<close> 
  for  "v"  :: " bool "

\<comment> \<open>\<open>val int_of_register_value : register_value -> maybe integer\<close>\<close>
fun int_of_register_value  :: \<open> register_value \<Rightarrow>(int)option \<close>  where 
     \<open> int_of_register_value (Regval_int v) = ( Some v )\<close> 
  for  "v"  :: " int "
|\<open> int_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_int : integer -> register_value\<close>\<close>
definition register_value_of_int  :: \<open> int \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_int v = ( Regval_int v )\<close> 
  for  "v"  :: " int "

\<comment> \<open>\<open>val real_of_register_value : register_value -> maybe real\<close>\<close>
fun real_of_register_value  :: \<open> register_value \<Rightarrow>(real)option \<close>  where 
     \<open> real_of_register_value (Regval_real v) = ( Some v )\<close> 
  for  "v"  :: " real "
|\<open> real_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_real : real -> register_value\<close>\<close>
definition register_value_of_real  :: \<open> real \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_real v = ( Regval_real v )\<close> 
  for  "v"  :: " real "

\<comment> \<open>\<open>val string_of_register_value : register_value -> maybe string\<close>\<close>
fun string_of_register_value  :: \<open> register_value \<Rightarrow>(string)option \<close>  where 
     \<open> string_of_register_value (Regval_string v) = ( Some v )\<close> 
  for  "v"  :: " string "
|\<open> string_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_string : string -> register_value\<close>\<close>
definition register_value_of_string  :: \<open> string \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_string v = ( Regval_string v )\<close> 
  for  "v"  :: " string "


definition instance_Sail2_values_Register_Value_Pmp_extract_types_register_value_dict  :: \<open>(register_value)Register_Value_class \<close>  where 
     \<open> instance_Sail2_values_Register_Value_Pmp_extract_types_register_value_dict = ((|

  bool_of_regval_method = bool_of_register_value,

  regval_of_bool_method = register_value_of_bool,

  int_of_regval_method = int_of_register_value,

  regval_of_int_method = register_value_of_int,

  real_of_regval_method = real_of_register_value,

  regval_of_real_method = register_value_of_real,

  string_of_regval_method = string_of_register_value,

  regval_of_string_method = register_value_of_string |) )\<close>

\<comment> \<open>\<open>val vector_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (list 'a)\<close>\<close>
fun vector_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a list)option \<close>  where 
     \<open> vector_of_regval of_regval1 (Regval_vector v) = ( just_list (List.map of_regval1 v))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)list "
|\<open> vector_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_vector : forall 'a. ('a -> register_value) -> list 'a -> register_value\<close>\<close>
definition regval_of_vector  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_vector regval_of1 xs = ( Regval_vector (List.map regval_of1 xs))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "xs"  :: " 'a list "


\<comment> \<open>\<open>val list_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (list 'a)\<close>\<close>
fun list_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a list)option \<close>  where 
     \<open> list_of_regval of_regval1 (Regval_list v) = ( just_list (List.map of_regval1 v))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)list "
|\<open> list_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_list : forall 'a. ('a -> register_value) -> list 'a -> register_value\<close>\<close>
definition regval_of_list  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_list regval_of1 xs = ( Regval_list (List.map regval_of1 xs))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "xs"  :: " 'a list "


\<comment> \<open>\<open>val option_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (maybe 'a)\<close>\<close>
fun option_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a option)option \<close>  where 
     \<open> option_of_regval of_regval1 (Regval_option v) = ( Some (Option.bind v of_regval1))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)option "
|\<open> option_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_option : forall 'a. ('a -> register_value) -> maybe 'a -> register_value\<close>\<close>
definition regval_of_option  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a option \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_option regval_of1 v = ( Regval_option (map_option regval_of1 v))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "v"  :: " 'a option "




\<comment> \<open>\<open>val registers : list (string * register_ops regstate register_value)\<close>\<close>
definition registers  :: \<open>(string*((regstate),(register_value))register_ops)list \<close>  where 
     \<open> registers = ( [

  ])\<close>


definition register_accessors  :: \<open>(string \<Rightarrow> unit \<Rightarrow>(register_value)option)*(string \<Rightarrow> register_value \<Rightarrow> unit \<Rightarrow>(unit)option)\<close>  where 
     \<open> register_accessors = ( mk_accessors ((\<lambda> nm .  Map.map_of registers nm)))\<close>


\<comment> \<open>\<open>val get_regval : string -> regstate -> maybe register_value\<close>\<close>
definition get_regval  :: \<open> string \<Rightarrow> unit \<Rightarrow>(register_value)option \<close>  where 
     \<open> get_regval = ( fst register_accessors )\<close>


\<comment> \<open>\<open>val set_regval : string -> register_value -> regstate -> maybe regstate\<close>\<close>
definition set_regval  :: \<open> string \<Rightarrow> register_value \<Rightarrow> unit \<Rightarrow>(unit)option \<close>  where 
     \<open> set_regval = ( snd register_accessors )\<close>




type_synonym( 'a, 'r) MR =" (register_value, regstate, 'a, 'r, unit) base_monadR "
type_synonym 'a M =" (register_value, regstate, 'a, unit) base_monad "
end
