chapter \<open>Generated by Lem from \<open>pmp_extract.lem\<close>.\<close>

theory "Pmp_extract" 

imports
  Main
  "LEM.Lem_pervasives_extra"
  "Sail2_instr_kinds"
  "Sail2_values"
  "Sail2_string"
  "Sail2_operators_bitlists"
  "Sail2_prompt_monad"
  "Sail2_prompt"
  "Sail2_undefined"
  "Pmp_extract_types"

begin 

\<comment> \<open>\<open>Generated by Sail from pmp_extract.sail\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>
\<comment> \<open>\<open>open import Sail2_string\<close>\<close>
\<comment> \<open>\<open>open import Sail2_operators_bitlists\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt_monad\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt\<close>\<close>
\<comment> \<open>\<open>open import Sail2_undefined\<close>\<close>
\<comment> \<open>\<open>open import Pmp_extract_types\<close>\<close>





\<comment> \<open>\<open>val neq_bool : bool -> bool -> bool\<close>\<close>

definition neq_bool  :: \<open> bool \<Rightarrow> bool \<Rightarrow> bool \<close>  where 
     \<open> neq_bool x y = ( (\<not> (((x = y)))))\<close> 
  for  "x"  :: " bool " 
  and  "y"  :: " bool "




\<comment> \<open>\<open>val __id : integer -> integer\<close>\<close>

definition id0  :: \<open> int \<Rightarrow> int \<close>  where 
     \<open> id0 x = ( x )\<close> 
  for  "x"  :: " int "


\<comment> \<open>\<open>val _shl_int_general : ii -> ii -> ii\<close>\<close>

definition shl_int_general  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> shl_int_general (m :: ii) (n :: ii) = (
   if ((n \<ge> (( 0 :: int)::ii))) then (shl_int m n)
   else (shr_int m ((- n))))\<close> 
  for  "m"  :: " int " 
  and  "n"  :: " int "


\<comment> \<open>\<open>val _shr_int_general : ii -> ii -> ii\<close>\<close>

definition shr_int_general  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> shr_int_general (m :: ii) (n :: ii) = (
   if ((n \<ge> (( 0 :: int)::ii))) then (shr_int m n)
   else (shl_int m ((- n))))\<close> 
  for  "m"  :: " int " 
  and  "n"  :: " int "


\<comment> \<open>\<open>val fdiv_int : ii -> ii -> ii\<close>\<close>

definition fdiv_int  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> fdiv_int (n :: ii) (m :: ii) = (
   if (((((n < (( 0 :: int)::ii))) \<and> ((m > (( 0 :: int)::ii)))))) then
     (((tdiv_int ((n + (( 1 :: int)::ii))) m)) - (( 1 :: int)::ii))
   else if (((((n > (( 0 :: int)::ii))) \<and> ((m < (( 0 :: int)::ii)))))) then
     (((tdiv_int ((n - (( 1 :: int)::ii))) m)) - (( 1 :: int)::ii))
   else (tdiv_int n m))\<close> 
  for  "n"  :: " int " 
  and  "m"  :: " int "


\<comment> \<open>\<open>val fmod_int : ii -> ii -> ii\<close>\<close>

definition fmod_int  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> fmod_int (n :: ii) (m :: ii) = ( (n - ((m * ((fdiv_int n m))))))\<close> 
  for  "n"  :: " int " 
  and  "m"  :: " int "


\<comment> \<open>\<open>val sail_mask : integer -> list bitU -> (list bitU)\<close>\<close>

definition sail_mask  :: \<open> int \<Rightarrow>(bitU)list \<Rightarrow>(bitU)list \<close>  where 
     \<open> sail_mask len v = (
   if ((len \<le> ((int (List.length v))))) then (vector_truncate v len)
   else (zero_extend v len))\<close> 
  for  "len"  :: " int " 
  and  "v"  :: "(bitU)list "


\<comment> \<open>\<open>val sail_ones : integer -> (list bitU)\<close>\<close>

definition sail_ones  :: \<open> int \<Rightarrow>(bitU)list \<close>  where 
     \<open> sail_ones n = ( (not_vec ((zeros n))))\<close> 
  for  "n"  :: " int "


\<comment> \<open>\<open>val slice_mask : integer -> ii -> ii -> (list bitU)\<close>\<close>

definition slice_mask  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow>(bitU)list \<close>  where 
     \<open> slice_mask n i l = (
   if ((l \<ge> n)) then (shiftl ((sail_ones n)) i)
   else
     (let (one :: bitU list) = (sail_mask n [B1]) in
     (shiftl ((sub_vec ((shiftl one l)) one)) i)))\<close> 
  for  "n"  :: " int " 
  and  "i"  :: " int " 
  and  "l"  :: " int "


\<comment> \<open>\<open>val to_bytes_le : integer -> list bitU -> (list (list bitU))\<close>\<close>

definition to_bytes_le  :: \<open> int \<Rightarrow>(bitU)list \<Rightarrow>((bitU)list)list \<close>  where 
     \<open> to_bytes_le n b = (
   (let res = (vector_init n ((zeros (( 8 :: int)::ii)))) in
   (let loop_i_lower = ((( 0 :: int)::ii)) in
   (let loop_i_upper = (n - (( 1 :: int)::ii)) in
   (foreach (index_list loop_i_lower loop_i_upper (( 1 :: int)::ii)) res
     ((\<lambda> i res . 
       (update_list_dec res i
          ((subrange_vec_dec b (((((( 8 :: int)::ii) * i)) + (( 7 :: int)::ii)))
              (((( 8 :: int)::ii) * i))))))))))))\<close> 
  for  "n"  :: " int " 
  and  "b"  :: "(bitU)list "


\<comment> \<open>\<open>val from_bytes_le : integer -> list (list bitU) -> (list bitU)\<close>\<close>

definition from_bytes_le  :: \<open> int \<Rightarrow>((bitU)list)list \<Rightarrow>(bitU)list \<close>  where 
     \<open> from_bytes_le n v = (
   (let res = (zeros (((( 8 :: int)::ii) * n))) in
   (let loop_i_lower = ((( 0 :: int)::ii)) in
   (let loop_i_upper = (n - (( 1 :: int)::ii)) in
   (foreach (index_list loop_i_lower loop_i_upper (( 1 :: int)::ii)) res
     ((\<lambda> i res . 
       (update_subrange_vec_dec res (((((( 8 :: int)::ii) * i)) + (( 7 :: int)::ii)))
          (((( 8 :: int)::ii) * i)) ((access_list_dec v i))))))))))\<close> 
  for  "n"  :: " int " 
  and  "v"  :: "((bitU)list)list "


\<comment> \<open>\<open>val is_none : forall 'a. maybe 'a -> bool\<close>\<close>

fun is_none  :: \<open> 'a option \<Rightarrow> bool \<close>  where 
     \<open> is_none (Some (_)) = ( False )\<close>
|\<open> is_none None = ( True )\<close>


\<comment> \<open>\<open>val is_some : forall 'a. maybe 'a -> bool\<close>\<close>

fun is_some  :: \<open> 'a option \<Rightarrow> bool \<close>  where 
     \<open> is_some (Some (_)) = ( True )\<close>
|\<open> is_some None = ( False )\<close>


\<comment> \<open>\<open>val concat_str_bits : string -> list bitU -> string\<close>\<close>

definition concat_str_bits  :: \<open> string \<Rightarrow>(bitU)list \<Rightarrow> string \<close>  where 
     \<open> concat_str_bits str x = ( ((@) str ((string_of_bits x))))\<close> 
  for  "str"  :: " string " 
  and  "x"  :: "(bitU)list "


\<comment> \<open>\<open>val concat_str_dec : string -> ii -> string\<close>\<close>

definition concat_str_dec  :: \<open> string \<Rightarrow> int \<Rightarrow> string \<close>  where 
     \<open> concat_str_dec str x = ( ((@) str ((dec_str x))))\<close> 
  for  "str"  :: " string " 
  and  "x"  :: " int "


\<comment> \<open>\<open>val undefined_pmpAddrMatch : unit -> M pmpAddrMatch\<close>\<close>

definition undefined_pmpAddrMatch  :: \<open> unit \<Rightarrow>((register_value),(pmpAddrMatch),(unit))monad \<close>  where 
     \<open> undefined_pmpAddrMatch _ = ( (internal_pick 
  instance_Sail2_values_Register_Value_Pmp_extract_types_register_value_dict [PMP_NoMatch,PMP_PartialMatch,PMP_Match]))\<close>


\<comment> \<open>\<open>val pmpAddrMatch_of_num : integer -> pmpAddrMatch\<close>\<close>

definition pmpAddrMatch_of_num  :: \<open> int \<Rightarrow> pmpAddrMatch \<close>  where 
     \<open> pmpAddrMatch_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then PMP_NoMatch
   else if (((l__0 = (( 1 :: int)::ii)))) then PMP_PartialMatch
   else PMP_Match))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_pmpAddrMatch : pmpAddrMatch -> (integer)\<close>\<close>

fun num_of_pmpAddrMatch  :: \<open> pmpAddrMatch \<Rightarrow> int \<close>  where 
     \<open> num_of_pmpAddrMatch PMP_NoMatch = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_pmpAddrMatch PMP_PartialMatch = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_pmpAddrMatch PMP_Match = ( (( 2 :: int)::ii))\<close>


\<comment> \<open>\<open>val pmpRangeMatch : ii -> ii -> ii -> ii -> pmpAddrMatch\<close>\<close>

definition pmpRangeMatch  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow> pmpAddrMatch \<close>  where 
     \<open> pmpRangeMatch (begin1 :: ii) (end1 :: ii) (addr :: ii) (width :: ii) = (
   if (((((((addr + width)) \<le> begin1)) \<or> ((end1 \<le> addr))))) then PMP_NoMatch
   else if (((((begin1 \<le> addr)) \<and> ((((addr + width)) \<le> end1))))) then PMP_Match
   else PMP_PartialMatch )\<close> 
  for  "begin1"  :: " int " 
  and  "end1"  :: " int " 
  and  "addr"  :: " int " 
  and  "width"  :: " int "


\<comment> \<open>\<open>val napot_region : list bitU -> (ii * ii)\<close>\<close>

definition napot_region  :: \<open>(bitU)list \<Rightarrow> int*int \<close>  where 
     \<open> napot_region pmpaddr = (
   (let mask1 = (xor_vec pmpaddr ((add_vec_int pmpaddr (( 1 :: int)::ii)))) in
   (let begin_words = (uint0 ((and_vec pmpaddr ((not_vec mask1))))) in
   (let end_words = (((begin_words + ((uint0 mask1)))) + (( 1 :: int)::ii)) in
   ((begin_words * (( 4 :: int)::ii)), (end_words * (( 4 :: int)::ii)))))))\<close> 
  for  "pmpaddr"  :: "(bitU)list "


\<comment> \<open>\<open>val initialize_registers : unit -> unit\<close>\<close>

definition initialize_registers  :: \<open> unit \<Rightarrow> unit \<close>  where 
     \<open> initialize_registers _ = ( ()  )\<close>


end
