chapter \<open>Generated by Lem from \<open>pmp_official_body_mw.lem\<close>.\<close>

theory "Pmp_official_body_mw" 

imports
  Main
  "LEM.Lem_pervasives_extra"
  "Sail2_instr_kinds"
  "Sail2_values"
  "Sail2_string"
  "Sail2_operators_mwords"
  "Sail2_prompt_monad"
  "Sail2_prompt"
  "Sail2_undefined"
  "Pmp_official_body_mw_types"

begin 

\<comment> \<open>\<open>Generated by Sail from pmp_official_body_mw.sail\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>
\<comment> \<open>\<open>open import Sail2_string\<close>\<close>
\<comment> \<open>\<open>open import Sail2_operators_mwords\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt_monad\<close>\<close>
\<comment> \<open>\<open>open import Sail2_prompt\<close>\<close>
\<comment> \<open>\<open>open import Sail2_undefined\<close>\<close>
\<comment> \<open>\<open>open import Pmp_official_body_mw_types\<close>\<close>





\<comment> \<open>\<open>val neq_bool : bool -> bool -> bool\<close>\<close>

definition neq_bool  :: \<open> bool \<Rightarrow> bool \<Rightarrow> bool \<close>  where 
     \<open> neq_bool x y = ( (\<not> (((x = y)))))\<close> 
  for  "x"  :: " bool " 
  and  "y"  :: " bool "




\<comment> \<open>\<open>val __id : integer -> integer\<close>\<close>

definition id0  :: \<open> int \<Rightarrow> int \<close>  where 
     \<open> id0 x = ( x )\<close> 
  for  "x"  :: " int "


\<comment> \<open>\<open>val _shl_int_general : ii -> ii -> ii\<close>\<close>

definition shl_int_general  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> shl_int_general (m :: ii) (n :: ii) = (
   if ((n \<ge> (( 0 :: int)::ii))) then (shl_int m n)
   else (shr_int m ((- n))))\<close> 
  for  "m"  :: " int " 
  and  "n"  :: " int "


\<comment> \<open>\<open>val _shr_int_general : ii -> ii -> ii\<close>\<close>

definition shr_int_general  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> shr_int_general (m :: ii) (n :: ii) = (
   if ((n \<ge> (( 0 :: int)::ii))) then (shr_int m n)
   else (shl_int m ((- n))))\<close> 
  for  "m"  :: " int " 
  and  "n"  :: " int "


\<comment> \<open>\<open>val fdiv_int : ii -> ii -> ii\<close>\<close>

definition fdiv_int  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> fdiv_int (n :: ii) (m :: ii) = (
   if (((((n < (( 0 :: int)::ii))) \<and> ((m > (( 0 :: int)::ii)))))) then
     (((tdiv_int ((n + (( 1 :: int)::ii))) m)) - (( 1 :: int)::ii))
   else if (((((n > (( 0 :: int)::ii))) \<and> ((m < (( 0 :: int)::ii)))))) then
     (((tdiv_int ((n - (( 1 :: int)::ii))) m)) - (( 1 :: int)::ii))
   else (tdiv_int n m))\<close> 
  for  "n"  :: " int " 
  and  "m"  :: " int "


\<comment> \<open>\<open>val fmod_int : ii -> ii -> ii\<close>\<close>

definition fmod_int  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<close>  where 
     \<open> fmod_int (n :: ii) (m :: ii) = ( (n - ((m * ((fdiv_int n m))))))\<close> 
  for  "n"  :: " int " 
  and  "m"  :: " int "


\<comment> \<open>\<open>val sail_mask : forall 'len 'v. Size 'len, Size 'v => integer -> mword 'v -> (mword 'len)\<close>\<close>

definition sail_mask  :: \<open> int \<Rightarrow>('v::len)Word.word \<Rightarrow>('len::len)Word.word \<close>  where 
     \<open> sail_mask len v = (
   if ((len \<le> ((int (size v))))) then (vector_truncate v len  :: ( 'len::len)Word.word)
   else (zero_extend v len  :: ( 'len::len)Word.word))\<close> 
  for  "len"  :: " int " 
  and  "v"  :: "('v::len)Word.word "


\<comment> \<open>\<open>val sail_ones : forall 'n. Size 'n => integer -> (mword 'n)\<close>\<close>

definition sail_ones  :: \<open> int \<Rightarrow>('n::len)Word.word \<close>  where 
     \<open> sail_ones n = ( (not_vec ((zeros n  :: ( 'n::len)Word.word))  :: ( 'n::len)Word.word))\<close> 
  for  "n"  :: " int "


\<comment> \<open>\<open>val slice_mask : forall 'n. Size 'n => integer -> ii -> ii -> (mword 'n)\<close>\<close>

definition slice_mask  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow>('n::len)Word.word \<close>  where 
     \<open> slice_mask n i l = (
   if ((l \<ge> n)) then (shiftl ((sail_ones n  :: ( 'n::len)Word.word)) i  :: ( 'n::len)Word.word)
   else
     (let (one :: ( 'n::len)Word.word) = ((sail_mask n ( 0b1 ::  1 Word.word)  :: ( 'n::len)Word.word)) in
     (shiftl ((sub_vec ((shiftl one l  :: ( 'n::len)Word.word)) one  :: ( 'n::len)Word.word)) i  :: ( 'n::len)Word.word)))\<close> 
  for  "n"  :: " int " 
  and  "i"  :: " int " 
  and  "l"  :: " int "


\<comment> \<open>\<open>val to_bytes_le : forall 'p8_times_n. Size 'p8_times_n => integer -> mword 'p8_times_n -> (list (mword ty8))\<close>\<close>

definition to_bytes_le  :: \<open> int \<Rightarrow>('p8_times_n::len)Word.word \<Rightarrow>((8)Word.word)list \<close>  where 
     \<open> to_bytes_le n b = (
   (let res = ((vector_init n ((zeros (( 8 :: int)::ii)  ::  8 Word.word))  :: ( 8 Word.word) list)) in
   (let loop_i_lower = ((( 0 :: int)::ii)) in
   (let loop_i_upper = (n - (( 1 :: int)::ii)) in
   (foreach (index_list loop_i_lower loop_i_upper (( 1 :: int)::ii)) res
     ((\<lambda> i res . 
       (update_list_dec res i ((slice b (((( 8 :: int)::ii) * i)) (( 8 :: int)::ii)  ::  8 Word.word))
         :: ( 8 Word.word) list))))))))\<close> 
  for  "n"  :: " int " 
  and  "b"  :: "('p8_times_n::len)Word.word "


\<comment> \<open>\<open>val from_bytes_le : forall 'p8_times_n. Size 'p8_times_n => integer -> list (mword ty8) -> (mword 'p8_times_n)\<close>\<close>

definition from_bytes_le  :: \<open> int \<Rightarrow>((8)Word.word)list \<Rightarrow>('p8_times_n::len)Word.word \<close>  where 
     \<open> from_bytes_le n v = (
   (let res = ((zeros (((( 8 :: int)::ii) * n))  :: ( 'p8_times_n::len)Word.word)) in
   (let loop_i_lower = ((( 0 :: int)::ii)) in
   (let loop_i_upper = (n - (( 1 :: int)::ii)) in
   (foreach (index_list loop_i_lower loop_i_upper (( 1 :: int)::ii)) res
     ((\<lambda> i res . 
       (update_subrange_vec_dec res (((((( 8 :: int)::ii) * i)) + (( 7 :: int)::ii)))
          (((( 8 :: int)::ii) * i)) ((access_list_dec v i  ::  8 Word.word))
         :: ( 'p8_times_n::len)Word.word))))))))\<close> 
  for  "n"  :: " int " 
  and  "v"  :: "((8)Word.word)list "


\<comment> \<open>\<open>val is_none : forall 'a. maybe 'a -> bool\<close>\<close>

fun is_none  :: \<open> 'a option \<Rightarrow> bool \<close>  where 
     \<open> is_none (Some (_)) = ( False )\<close>
|\<open> is_none None = ( True )\<close>


\<comment> \<open>\<open>val is_some : forall 'a. maybe 'a -> bool\<close>\<close>

fun is_some  :: \<open> 'a option \<Rightarrow> bool \<close>  where 
     \<open> is_some (Some (_)) = ( True )\<close>
|\<open> is_some None = ( False )\<close>


\<comment> \<open>\<open>val concat_str_bits : forall 'n. Size 'n => string -> mword 'n -> string\<close>\<close>

definition concat_str_bits  :: \<open> string \<Rightarrow>('n::len)Word.word \<Rightarrow> string \<close>  where 
     \<open> concat_str_bits str x = ( ((@) str ((string_of_bits x))))\<close> 
  for  "str"  :: " string " 
  and  "x"  :: "('n::len)Word.word "


\<comment> \<open>\<open>val concat_str_dec : string -> ii -> string\<close>\<close>

definition concat_str_dec  :: \<open> string \<Rightarrow> int \<Rightarrow> string \<close>  where 
     \<open> concat_str_dec str x = ( ((@) str ((dec_str x))))\<close> 
  for  "str"  :: " string " 
  and  "x"  :: " int "


\<comment> \<open>\<open>val undefined_pmpAddrMatch : unit -> M pmpAddrMatch\<close>\<close>

definition undefined_pmpAddrMatch  :: \<open> unit \<Rightarrow>((register_value),(pmpAddrMatch),(unit))monad \<close>  where 
     \<open> undefined_pmpAddrMatch _ = ( (internal_pick 
  instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict [PMP_NoMatch,PMP_PartialMatch,PMP_Match]))\<close>


\<comment> \<open>\<open>val pmpAddrMatch_of_num : integer -> pmpAddrMatch\<close>\<close>

definition pmpAddrMatch_of_num  :: \<open> int \<Rightarrow> pmpAddrMatch \<close>  where 
     \<open> pmpAddrMatch_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then PMP_NoMatch
   else if (((l__0 = (( 1 :: int)::ii)))) then PMP_PartialMatch
   else PMP_Match))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_pmpAddrMatch : pmpAddrMatch -> (integer)\<close>\<close>

fun num_of_pmpAddrMatch  :: \<open> pmpAddrMatch \<Rightarrow> int \<close>  where 
     \<open> num_of_pmpAddrMatch PMP_NoMatch = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_pmpAddrMatch PMP_PartialMatch = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_pmpAddrMatch PMP_Match = ( (( 2 :: int)::ii))\<close>


\<comment> \<open>\<open>val undefined_PmpAddrMatchType : unit -> M PmpAddrMatchType\<close>\<close>

definition undefined_PmpAddrMatchType  :: \<open> unit \<Rightarrow>((register_value),(PmpAddrMatchType),(unit))monad \<close>  where 
     \<open> undefined_PmpAddrMatchType _ = ( (internal_pick 
  instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict [OFF,TOR,NA4,NAPOT]))\<close>


\<comment> \<open>\<open>val PmpAddrMatchType_of_num : integer -> PmpAddrMatchType\<close>\<close>

definition PmpAddrMatchType_of_num  :: \<open> int \<Rightarrow> PmpAddrMatchType \<close>  where 
     \<open> PmpAddrMatchType_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then OFF
   else if (((l__0 = (( 1 :: int)::ii)))) then TOR
   else if (((l__0 = (( 2 :: int)::ii)))) then NA4
   else NAPOT))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_PmpAddrMatchType : PmpAddrMatchType -> (integer)\<close>\<close>

fun num_of_PmpAddrMatchType  :: \<open> PmpAddrMatchType \<Rightarrow> int \<close>  where 
     \<open> num_of_PmpAddrMatchType OFF = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_PmpAddrMatchType TOR = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_PmpAddrMatchType NA4 = ( (( 2 :: int)::ii))\<close>
|\<open> num_of_PmpAddrMatchType NAPOT = ( (( 3 :: int)::ii))\<close>


\<comment> \<open>\<open>val undefined_Privilege : unit -> M Privilege\<close>\<close>

definition undefined_Privilege  :: \<open> unit \<Rightarrow>((register_value),(Privilege),(unit))monad \<close>  where 
     \<open> undefined_Privilege _ = ( (internal_pick 
  instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict [User,VirtualUser,Supervisor,VirtualSupervisor,Machine]))\<close>


\<comment> \<open>\<open>val Privilege_of_num : integer -> Privilege\<close>\<close>

definition Privilege_of_num  :: \<open> int \<Rightarrow> Privilege \<close>  where 
     \<open> Privilege_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then User
   else if (((l__0 = (( 1 :: int)::ii)))) then VirtualUser
   else if (((l__0 = (( 2 :: int)::ii)))) then Supervisor
   else if (((l__0 = (( 3 :: int)::ii)))) then VirtualSupervisor
   else Machine))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_Privilege : Privilege -> (integer)\<close>\<close>

fun num_of_Privilege  :: \<open> Privilege \<Rightarrow> int \<close>  where 
     \<open> num_of_Privilege User = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_Privilege VirtualUser = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_Privilege Supervisor = ( (( 2 :: int)::ii))\<close>
|\<open> num_of_Privilege VirtualSupervisor = ( (( 3 :: int)::ii))\<close>
|\<open> num_of_Privilege Machine = ( (( 4 :: int)::ii))\<close>


\<comment> \<open>\<open>val undefined_PmpAccess : unit -> M PmpAccess\<close>\<close>

definition undefined_PmpAccess  :: \<open> unit \<Rightarrow>((register_value),(PmpAccess),(unit))monad \<close>  where 
     \<open> undefined_PmpAccess _ = (
   (internal_pick instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict
      [Access_Load_Data,Access_Load_Vector,Access_Load_PageTableEntry,Access_Load_ShadowStack,Access_LoadReserved_Data,Access_Store_Data,Access_Store_Vector,Access_Store_PageTableEntry,Access_Store_ShadowStack,Access_StoreConditional_Data,Access_Atomic_Data_Data,Access_Atomic_ShadowStack_ShadowStack,Access_InstructionFetch,Access_Cache_CB_manage,Access_Cache_CB_zero,Access_Cache_Prefetch_I,Access_Cache_Prefetch_R,Access_Cache_Prefetch_W]))\<close>


\<comment> \<open>\<open>val PmpAccess_of_num : integer -> PmpAccess\<close>\<close>

definition PmpAccess_of_num  :: \<open> int \<Rightarrow> PmpAccess \<close>  where 
     \<open> PmpAccess_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then Access_Load_Data
   else if (((l__0 = (( 1 :: int)::ii)))) then Access_Load_Vector
   else if (((l__0 = (( 2 :: int)::ii)))) then Access_Load_PageTableEntry
   else if (((l__0 = (( 3 :: int)::ii)))) then Access_Load_ShadowStack
   else if (((l__0 = (( 4 :: int)::ii)))) then Access_LoadReserved_Data
   else if (((l__0 = (( 5 :: int)::ii)))) then Access_Store_Data
   else if (((l__0 = (( 6 :: int)::ii)))) then Access_Store_Vector
   else if (((l__0 = (( 7 :: int)::ii)))) then Access_Store_PageTableEntry
   else if (((l__0 = (( 8 :: int)::ii)))) then Access_Store_ShadowStack
   else if (((l__0 = (( 9 :: int)::ii)))) then Access_StoreConditional_Data
   else if (((l__0 = (( 10 :: int)::ii)))) then Access_Atomic_Data_Data
   else if (((l__0 = (( 11 :: int)::ii)))) then Access_Atomic_ShadowStack_ShadowStack
   else if (((l__0 = (( 12 :: int)::ii)))) then Access_InstructionFetch
   else if (((l__0 = (( 13 :: int)::ii)))) then Access_Cache_CB_manage
   else if (((l__0 = (( 14 :: int)::ii)))) then Access_Cache_CB_zero
   else if (((l__0 = (( 15 :: int)::ii)))) then Access_Cache_Prefetch_I
   else if (((l__0 = (( 16 :: int)::ii)))) then Access_Cache_Prefetch_R
   else Access_Cache_Prefetch_W))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_PmpAccess : PmpAccess -> (integer)\<close>\<close>

fun num_of_PmpAccess  :: \<open> PmpAccess \<Rightarrow> int \<close>  where 
     \<open> num_of_PmpAccess Access_Load_Data = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Load_Vector = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Load_PageTableEntry = ( (( 2 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Load_ShadowStack = ( (( 3 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_LoadReserved_Data = ( (( 4 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Store_Data = ( (( 5 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Store_Vector = ( (( 6 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Store_PageTableEntry = ( (( 7 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Store_ShadowStack = ( (( 8 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_StoreConditional_Data = ( (( 9 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Atomic_Data_Data = ( (( 10 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Atomic_ShadowStack_ShadowStack = ( (( 11 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_InstructionFetch = ( (( 12 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Cache_CB_manage = ( (( 13 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Cache_CB_zero = ( (( 14 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Cache_Prefetch_I = ( (( 15 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Cache_Prefetch_R = ( (( 16 :: int)::ii))\<close>
|\<open> num_of_PmpAccess Access_Cache_Prefetch_W = ( (( 17 :: int)::ii))\<close>


\<comment> \<open>\<open>val undefined_PmpException : unit -> M PmpException\<close>\<close>

definition undefined_PmpException  :: \<open> unit \<Rightarrow>((register_value),(PmpException),(unit))monad \<close>  where 
     \<open> undefined_PmpException _ = (
   (internal_pick instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict [E_Fetch_Access_Fault,E_Load_Access_Fault,E_SAMO_Access_Fault]))\<close>


\<comment> \<open>\<open>val PmpException_of_num : integer -> PmpException\<close>\<close>

definition PmpException_of_num  :: \<open> int \<Rightarrow> PmpException \<close>  where 
     \<open> PmpException_of_num arg1 = (
   (let l__0 = arg1 in
   if (((l__0 = (( 0 :: int)::ii)))) then E_Fetch_Access_Fault
   else if (((l__0 = (( 1 :: int)::ii)))) then E_Load_Access_Fault
   else E_SAMO_Access_Fault))\<close> 
  for  "arg1"  :: " int "


\<comment> \<open>\<open>val num_of_PmpException : PmpException -> (integer)\<close>\<close>

fun num_of_PmpException  :: \<open> PmpException \<Rightarrow> int \<close>  where 
     \<open> num_of_PmpException E_Fetch_Access_Fault = ( (( 0 :: int)::ii))\<close>
|\<open> num_of_PmpException E_Load_Access_Fault = ( (( 1 :: int)::ii))\<close>
|\<open> num_of_PmpException E_SAMO_Access_Fault = ( (( 2 :: int)::ii))\<close>


\<comment> \<open>\<open>val undefined_Pmpcfg_ent : unit -> M Pmpcfg_ent\<close>\<close>

definition undefined_Pmpcfg_ent  :: \<open> unit \<Rightarrow>((register_value),(Pmpcfg_ent),(unit))monad \<close>  where 
     \<open> undefined_Pmpcfg_ent _ = (
   (undefined_bool instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict () ) \<bind> ((\<lambda> (w__0 :: bool) . 
   (undefined_bool instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict () ) \<bind> ((\<lambda> (w__1 :: bool) . 
   (undefined_bool instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict () ) \<bind> ((\<lambda> (w__2 :: bool) . 
   (undefined_PmpAddrMatchType () ) \<bind> ((\<lambda> (w__3 :: PmpAddrMatchType) . 
   (undefined_bool instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict () ) \<bind> ((\<lambda> (w__4 :: bool) . 
   return ((| Pmpcfg_ent_cfg_R = w__0,
              Pmpcfg_ent_cfg_W = w__1,
              Pmpcfg_ent_cfg_X = w__2,
              Pmpcfg_ent_cfg_A = w__3,
              Pmpcfg_ent_cfg_L = w__4 |)))))))))))))\<close>


\<comment> \<open>\<open>val undefined_PmpRawEntry : unit -> M PmpRawEntry\<close>\<close>

definition undefined_PmpRawEntry  :: \<open> unit \<Rightarrow>((register_value),(PmpRawEntry),(unit))monad \<close>  where 
     \<open> undefined_PmpRawEntry _ = (
   (undefined_bitvector 
  instance_Sail2_values_Bitvector_Machine_word_mword_dict instance_Sail2_values_Register_Value_Pmp_official_body_mw_types_register_value_dict (( 64 :: int)::ii)  :: ( 64 Word.word) M) \<bind> ((\<lambda> (w__0 ::  64 Word.word) . 
   (undefined_Pmpcfg_ent () ) \<bind> ((\<lambda> (w__1 :: Pmpcfg_ent) . 
   return ((| PmpRawEntry_raw_addr = w__0,
              PmpRawEntry_raw_cfg = w__1 |)))))))\<close>


\<comment> \<open>\<open>val accessFaultFromAccessType : PmpAccess -> PmpException\<close>\<close>

fun accessFaultFromAccessType  :: \<open> PmpAccess \<Rightarrow> PmpException \<close>  where 
     \<open> accessFaultFromAccessType Access_InstructionFetch = ( E_Fetch_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Load_Data = ( E_Load_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Load_Vector = ( E_Load_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Load_PageTableEntry = ( E_Load_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_LoadReserved_Data = ( E_Load_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Store_Data = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Store_Vector = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Store_PageTableEntry = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_StoreConditional_Data = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Atomic_Data_Data = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Load_ShadowStack = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Store_ShadowStack = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Atomic_ShadowStack_ShadowStack = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Cache_CB_manage = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Cache_CB_zero = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Cache_Prefetch_R = ( E_Load_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Cache_Prefetch_W = ( E_SAMO_Access_Fault )\<close>
|\<open> accessFaultFromAccessType Access_Cache_Prefetch_I = ( E_Fetch_Access_Fault )\<close>


\<comment> \<open>\<open>val pmpCheckRWX : Pmpcfg_ent -> PmpAccess -> bool\<close>\<close>

fun pmpCheckRWX  :: \<open> Pmpcfg_ent \<Rightarrow> PmpAccess \<Rightarrow> bool \<close>  where 
     \<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Load_Data :: PmpAccess) = ((Pmpcfg_ent_cfg_R   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Load_Vector :: PmpAccess) = ((Pmpcfg_ent_cfg_R   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Load_PageTableEntry :: PmpAccess) = ((Pmpcfg_ent_cfg_R   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_LoadReserved_Data :: PmpAccess) = ((Pmpcfg_ent_cfg_R   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Store_Data :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Store_Vector :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Store_PageTableEntry :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_StoreConditional_Data :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Atomic_Data_Data :: PmpAccess) = ( (((Pmpcfg_ent_cfg_R   ent) \<and>(Pmpcfg_ent_cfg_W   ent))))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_InstructionFetch :: PmpAccess) = ((Pmpcfg_ent_cfg_X   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Load_ShadowStack :: PmpAccess) = ( (((Pmpcfg_ent_cfg_R   ent) \<and>(Pmpcfg_ent_cfg_W   ent))))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Store_ShadowStack :: PmpAccess) = ( (((Pmpcfg_ent_cfg_R   ent) \<and>(Pmpcfg_ent_cfg_W   ent))))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Atomic_ShadowStack_ShadowStack :: PmpAccess) = ( (((Pmpcfg_ent_cfg_R   ent) \<and>(Pmpcfg_ent_cfg_W   ent))))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Cache_CB_manage :: PmpAccess) = ( (((Pmpcfg_ent_cfg_R   ent) \<or>(Pmpcfg_ent_cfg_W   ent))))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Cache_CB_zero :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Cache_Prefetch_I :: PmpAccess) = ((Pmpcfg_ent_cfg_X   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Cache_Prefetch_R :: PmpAccess) = ((Pmpcfg_ent_cfg_R   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "
|\<open> pmpCheckRWX (ent :: Pmpcfg_ent) (Access_Cache_Prefetch_W :: PmpAccess) = ((Pmpcfg_ent_cfg_W   ent))\<close> 
  for  "ent"  :: " Pmpcfg_ent "


\<comment> \<open>\<open>val pmpLocked : Pmpcfg_ent -> bool\<close>\<close>

definition pmpLocked  :: \<open> Pmpcfg_ent \<Rightarrow> bool \<close>  where 
     \<open> pmpLocked cfg = ((Pmpcfg_ent_cfg_L   cfg))\<close> 
  for  "cfg"  :: " Pmpcfg_ent "


\<comment> \<open>\<open>val pmpRangeMatch : ii -> ii -> ii -> ii -> pmpAddrMatch\<close>\<close>

definition pmpRangeMatch  :: \<open> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow> int \<Rightarrow> pmpAddrMatch \<close>  where 
     \<open> pmpRangeMatch (begin1 :: ii) (end1 :: ii) (addr :: ii) (width :: ii) = (
   if (((((((addr + width)) \<le> begin1)) \<or> ((end1 \<le> addr))))) then PMP_NoMatch
   else if (((((begin1 \<le> addr)) \<and> ((((addr + width)) \<le> end1))))) then PMP_Match
   else PMP_PartialMatch )\<close> 
  for  "begin1"  :: " int " 
  and  "end1"  :: " int " 
  and  "addr"  :: " int " 
  and  "width"  :: " int "


\<comment> \<open>\<open>val pmpaddrAddr : mword ty64 -> ii\<close>\<close>

definition pmpaddrAddr  :: \<open>(64)Word.word \<Rightarrow> int \<close>  where 
     \<open> pmpaddrAddr pmpaddr = ( (((Word.uint pmpaddr)) * (( 4 :: int)::ii)))\<close> 
  for  "pmpaddr"  :: "(64)Word.word "


\<comment> \<open>\<open>val napotRegion : mword ty64 -> (ii * ii)\<close>\<close>

definition napotRegion  :: \<open>(64)Word.word \<Rightarrow> int*int \<close>  where 
     \<open> napotRegion pmpaddr = (
   (let mask1 = ((xor_vec pmpaddr ((add_vec_int pmpaddr (( 1 :: int)::ii)  ::  64 Word.word))  ::  64 Word.word)) in
   (let begin_words = (Word.uint ((and_vec pmpaddr ((not_vec mask1  ::  64 Word.word))  ::  64 Word.word))) in
   (let end_words = (((begin_words + ((Word.uint mask1)))) + (( 1 :: int)::ii)) in
   ((begin_words * (( 4 :: int)::ii)), (end_words * (( 4 :: int)::ii)))))))\<close> 
  for  "pmpaddr"  :: "(64)Word.word "


\<comment> \<open>\<open>val pmpMatchAddr : ii -> ii -> Pmpcfg_ent -> mword ty64 -> mword ty64 -> pmpAddrMatch\<close>\<close>

definition pmpMatchAddr  :: \<open> int \<Rightarrow> int \<Rightarrow> Pmpcfg_ent \<Rightarrow>(64)Word.word \<Rightarrow>(64)Word.word \<Rightarrow> pmpAddrMatch \<close>  where 
     \<open> pmpMatchAddr (addr :: ii) (width :: ii) (ent :: Pmpcfg_ent) (pmpaddr :: 64 bits) (prev_pmpaddr :: 64
  bits) = (
   (case (Pmpcfg_ent_cfg_A   ent) of
     OFF => PMP_NoMatch
   | TOR =>
      if ((((Word.uint prev_pmpaddr)) \<ge> ((Word.uint pmpaddr)))) then PMP_NoMatch
      else (pmpRangeMatch ((pmpaddrAddr prev_pmpaddr)) ((pmpaddrAddr pmpaddr)) addr width)
   | NA4 =>
      (let begin1 = (pmpaddrAddr pmpaddr) in
      (pmpRangeMatch begin1 ((begin1 + (( 4 :: int)::ii))) addr width))
   | NAPOT =>
      (let (begin1, end1) = (napotRegion pmpaddr) in
      (pmpRangeMatch begin1 end1 addr width))
   ))\<close> 
  for  "addr"  :: " int " 
  and  "width"  :: " int " 
  and  "ent"  :: " Pmpcfg_ent " 
  and  "pmpaddr"  :: "(64)Word.word " 
  and  "prev_pmpaddr"  :: "(64)Word.word "


\<comment> \<open>\<open>val pmpCheckFromPrev : mword ty64 -> list PmpRawEntry -> ii -> ii -> PmpAccess -> Privilege -> (maybe PmpException)\<close>\<close>

function (sequential,domintros)  pmpCheckFromPrev  :: \<open>(64)Word.word \<Rightarrow>(PmpRawEntry)list \<Rightarrow> int \<Rightarrow> int \<Rightarrow> PmpAccess \<Rightarrow> Privilege \<Rightarrow>(PmpException)option \<close>  where 
     \<open> pmpCheckFromPrev (prev :: 64 bits) (([]) :: PmpRawEntry list) (addr :: ii) (width :: ii) (access ::
  PmpAccess) (priv :: Privilege) = ( (case  priv of   Machine => None | _ => Some ((accessFaultFromAccessType access)) ))\<close> 
  for  "prev"  :: "(64)Word.word " 
  and  "addr"  :: " int " 
  and  "width"  :: " int " 
  and  "access"  :: " PmpAccess " 
  and  "priv"  :: " Privilege "
|\<open> pmpCheckFromPrev (prev :: 64 bits) ((ent # rest) :: PmpRawEntry list) (addr :: ii) (width :: ii) (access ::
  PmpAccess) (priv :: Privilege) = (
      (case  ((pmpMatchAddr addr width(PmpRawEntry_raw_cfg   ent)(PmpRawEntry_raw_addr   ent) prev)) of
        PMP_NoMatch =>
         (pmpCheckFromPrev(PmpRawEntry_raw_addr   ent) rest addr width access priv
           ::  PmpException option)
      | PMP_PartialMatch => Some ((accessFaultFromAccessType access))
      | PMP_Match =>
         if (((((pmpCheckRWX(PmpRawEntry_raw_cfg   ent) access)) \<or> ((case  priv of
                  Machine => if ((pmpLocked(PmpRawEntry_raw_cfg   ent))) then False else True
                | _ => False
                ))))) then
           None
         else Some ((accessFaultFromAccessType access))
      ))\<close> 
  for  "prev"  :: "(64)Word.word " 
  and  "ent"  :: " PmpRawEntry " 
  and  "rest"  :: "(PmpRawEntry)list " 
  and  "addr"  :: " int " 
  and  "width"  :: " int " 
  and  "access"  :: " PmpAccess " 
  and  "priv"  :: " Privilege " 
by pat_completeness auto


\<comment> \<open>\<open>val pmpCheckOfficialBody : list PmpRawEntry -> ii -> ii -> PmpAccess -> Privilege -> (maybe PmpException)\<close>\<close>

definition pmpCheckOfficialBody  :: \<open>(PmpRawEntry)list \<Rightarrow> int \<Rightarrow> int \<Rightarrow> PmpAccess \<Rightarrow> Privilege \<Rightarrow>(PmpException)option \<close>  where 
     \<open> pmpCheckOfficialBody (entries :: PmpRawEntry list) (addr :: ii) (width :: ii) (access :: PmpAccess) (priv ::
  Privilege) = (
   (pmpCheckFromPrev ( 0x0000000000000000 ::  64 Word.word) entries addr width access priv
     ::  PmpException option))\<close> 
  for  "entries"  :: "(PmpRawEntry)list " 
  and  "addr"  :: " int " 
  and  "width"  :: " int " 
  and  "access"  :: " PmpAccess " 
  and  "priv"  :: " Privilege "


\<comment> \<open>\<open>val initialize_registers : unit -> unit\<close>\<close>

definition initialize_registers  :: \<open> unit \<Rightarrow> unit \<close>  where 
     \<open> initialize_registers _ = ( ()  )\<close>


end
