chapter \<open>Generated by Lem from \<open>/tmp/sesbi-full-official-isabelle/20260701T091640Z-2/model/rv64d_types.lem\<close>.\<close>

theory "Rv64d_types" 

imports
  Main
  "LEM.Lem_pervasives_extra"
  "Sail.Sail2_instr_kinds"
  "Sail.Sail2_values"
  "Sail.Sail2_operators_bitlists"
  "Sail.Sail2_concurrency_interface"
  "Sail.Sail2_monadic_combinators"
  "Sail.Sail2_undefined_concurrency_interface"
  "Sail.Sail2_string"
  "Sail.Sail2_concurrency_interface_bitlists"

begin 

\<comment> \<open>\<open>Generated by Sail: types and register state\<close>\<close>
\<comment> \<open>\<open>open import Pervasives_extra\<close>\<close>
\<comment> \<open>\<open>open import Sail2_instr_kinds\<close>\<close>
\<comment> \<open>\<open>open import Sail2_values\<close>\<close>
\<comment> \<open>\<open>open import Sail2_string\<close>\<close>
\<comment> \<open>\<open>open import Sail2_operators_bitlists\<close>\<close>
\<comment> \<open>\<open>open import Sail2_concurrency_interface\<close>\<close>
\<comment> \<open>\<open>open import Sail2_monadic_combinators\<close>\<close>
\<comment> \<open>\<open>open import Sail2_undefined_concurrency_interface\<close>\<close>
\<comment> \<open>\<open>open import Sail2_concurrency_interface_bitlists\<close>\<close>



type_synonym bit0  =" bitU list "


datatype IsaVersion =   Isa_20191213 | Isa_Draft_20211102 | Isa_20211203 | Isa_20240411 | Isa_Latest



datatype vector_support =   Disabled | Integer | Float_single | Float_double | Full



type_synonym bits  =" bitU list "


datatype regidx  =   Regidx " ( bitU list)"







type_synonym xlenbits  =" bitU list "


datatype virtaddr  =   Virtaddr " ( bitU list)"



type_synonym fp_exception_flags  =" bitU list "


type_synonym fp_rounding_modes  =" bitU list "




type_synonym fp_bits  =" ( bitU list)"


record float_bits  =
  
 float_bits_sign ::" bitU list " 
 float_bits_exp ::" bitU list " 
 float_bits_mantissa ::" bitU list "  



datatype float_class =
    Float_class_negative_inf
  | Float_class_negative_normal
  | Float_class_negative_subnormal
  | Float_class_negative_zero
  | Float_class_positive_zero
  | Float_class_positive_subnormal
  | Float_class_positive_normal
  | Float_class_positive_inf
  | Float_class_snan
  | Float_class_qnan



type_synonym nat1  =" int "


datatype Signedness =   Signed | Unsigned



datatype VectorHalf =   High | Low





type_synonym mem_access_width  =" int "


datatype exception  =
    Error_not_implemented " (string)"
  | Error_internal_error " (string)"
  | Error_reserved_behavior " (string)"



datatype amoop =
    AMOSWAP | AMOAND | AMOOR | AMOXOR | AMOADD | AMOMIN | AMOMAX | AMOMINU | AMOMAXU | AMOCAS



datatype cbop_zicbom =   CBO_CLEAN | CBO_FLUSH | CBO_INVAL



datatype cbop_zicbop =   PREFETCH_I | PREFETCH_R | PREFETCH_W



type_synonym pm_len  =" int "


datatype PM_Ext =   PM_SSNPM | PM_SMNPM | PM_SMMPM



datatype PointerMaskingMode =   PMM_Disabled | PMM_Reserved | PMM_PMLEN_7 | PMM_PMLEN_16













type_synonym asidbits  =" bitU list "








type_synonym flenbits  =" bitU list "










type_synonym physaddrbits  =" bitU list "


datatype physaddr  =   Physaddr " ( bitU list)"



type_synonym mem_meta  =" unit "


datatype write_kind0 =
    Write_plain0
  | Write_RISCV_release0
  | Write_RISCV_strong_release0
  | Write_RISCV_conditional0
  | Write_RISCV_conditional_release0
  | Write_RISCV_conditional_strong_release0



datatype read_kind0 =
    Read_plain0
  | Read_ifetch0
  | Read_RISCV_acquire0
  | Read_RISCV_strong_acquire0
  | Read_RISCV_reserved0
  | Read_RISCV_reserved_acquire0
  | Read_RISCV_reserved_strong_acquire0



datatype barrier_kind0 =
    Barrier_RISCV_rw_rw0
  | Barrier_RISCV_r_rw0
  | Barrier_RISCV_r_r0
  | Barrier_RISCV_rw_w0
  | Barrier_RISCV_w_w0
  | Barrier_RISCV_w_rw0
  | Barrier_RISCV_rw_r0
  | Barrier_RISCV_r_w0
  | Barrier_RISCV_w_r0
  | Barrier_RISCV_tso0
  | Barrier_RISCV_i0



record RISCV_strong_access  = 
 RISCV_strong_access_variety ::" Access_variety "  



type_synonym RVFI_DII_Instruction_Packet  =" bitU list "


type_synonym RVFI_DII_Execution_Packet_InstMetaData  =" bitU list "


type_synonym RVFI_DII_Execution_Packet_PC  =" bitU list "


type_synonym RVFI_DII_Execution_Packet_Ext_Integer  =" bitU list "


type_synonym RVFI_DII_Execution_Packet_Ext_MemAccess  =" bitU list "


type_synonym RVFI_DII_Execution_Packet_V1  =" bitU list "


type_synonym RVFI_DII_Execution_PacketV2  =" bitU list "


type_synonym tvec_alignment  =" int "


datatype misaligned_exception =   AccessFault | AlignmentException



datatype mem_payload =   Data | Vector | PageTableEntry | ShadowStack



datatype cacheop  =   CB_manage " (cbop_zicbom)" | CB_zero " (unit)" | CB_prefetch " (cbop_zicbop)"



datatype 'a MemoryAccessType =
    Load " ('a)"
  | Store " ('a)"
  | LoadReserved " ((bool * bool * 'a))"
  | StoreConditional " ((bool * bool * 'a))"
  | Atomic " ((amoop * bool * bool * 'a * 'a))"
  | InstructionFetch " (unit)"
  | CacheAccess " (cacheop)"



type_synonym csreg  =" bitU list "


type_synonym ext_exc_type  =" unit "


datatype breakpoint_cause =   Brk_Software | Brk_Hardware



datatype ExceptionType  =
    E_Fetch_Addr_Align " (unit)"
  | E_Fetch_Access_Fault " (unit)"
  | E_Illegal_Instr " (unit)"
  | E_Breakpoint " (breakpoint_cause)"
  | E_Load_Addr_Align " (unit)"
  | E_Load_Access_Fault " (unit)"
  | E_SAMO_Addr_Align " (unit)"
  | E_SAMO_Access_Fault " (unit)"
  | E_U_EnvCall " (unit)"
  | E_S_EnvCall " (unit)"
  | E_VS_EnvCall " (unit)"
  | E_M_EnvCall " (unit)"
  | E_Fetch_Page_Fault " (unit)"
  | E_Load_Page_Fault " (unit)"
  | E_Reserved_14 " (unit)"
  | E_SAMO_Page_Fault " (unit)"
  | E_Reserved_16 " (unit)"
  | E_Reserved_17 " (unit)"
  | E_Software_Check " (unit)"
  | E_Reserved_19 " (unit)"
  | E_Fetch_GPage_Fault " (unit)"
  | E_Load_GPage_Fault " (unit)"
  | E_Virtual_Instr " (unit)"
  | E_SAMO_GPage_Fault " (unit)"
  | E_Extension " (unit)"



datatype InterruptType =
    I_Reserved_0
  | I_S_Software
  | I_VS_Software
  | I_M_Software
  | I_Reserved_4
  | I_S_Timer
  | I_VS_Timer
  | I_M_Timer
  | I_Reserved_8
  | I_S_External
  | I_VS_External
  | I_M_External
  | I_SG_External
  | I_COF



datatype Architecture =   RV32 | RV64 | RV128



type_synonym Misa  =" bitU list "


datatype (plugins only: size) extension =
    Ext_M
  | Ext_A
  | Ext_F
  | Ext_D
  | Ext_B
  | Ext_V
  | Ext_S
  | Ext_U
  | Ext_H
  | Ext_Zibi
  | Ext_Zic64b
  | Ext_Zicbom
  | Ext_Zicbop
  | Ext_Zicboz
  | Ext_Zicfilp
  | Ext_Zicfiss
  | Ext_Zicntr
  | Ext_Zicond
  | Ext_Zicsr
  | Ext_Zifencei
  | Ext_Zihintntl
  | Ext_Zihintpause
  | Ext_Zihpm
  | Ext_Zimop
  | Ext_Zmmul
  | Ext_Zaamo
  | Ext_Zabha
  | Ext_Zacas
  | Ext_Zalrsc
  | Ext_Zawrs
  | Ext_Za64rs
  | Ext_Za128rs
  | Ext_Zfa
  | Ext_Zfbfmin
  | Ext_Zfh
  | Ext_Zfhmin
  | Ext_Zfinx
  | Ext_Zdinx
  | Ext_Zca
  | Ext_Zcb
  | Ext_Zcd
  | Ext_Zcf
  | Ext_Zcmop
  | Ext_C
  | Ext_Zba
  | Ext_Zbb
  | Ext_Zbc
  | Ext_Zbkb
  | Ext_Zbkc
  | Ext_Zbkx
  | Ext_Zbs
  | Ext_Ziccamoa
  | Ext_Ziccamoc
  | Ext_Ziccif
  | Ext_Zicclsm
  | Ext_Ziccrse
  | Ext_Zknd
  | Ext_Zkne
  | Ext_Zknh
  | Ext_Zkr
  | Ext_Zksed
  | Ext_Zksh
  | Ext_Zkt
  | Ext_Zhinx
  | Ext_Zhinxmin
  | Ext_Zvl32b
  | Ext_Zvl64b
  | Ext_Zvl128b
  | Ext_Zvl256b
  | Ext_Zvl512b
  | Ext_Zvl1024b
  | Ext_Zve32f
  | Ext_Zve32x
  | Ext_Zve64d
  | Ext_Zve64f
  | Ext_Zve64x
  | Ext_Zvabd
  | Ext_Zvfbfmin
  | Ext_Zvfbfwma
  | Ext_Zvfh
  | Ext_Zvfhmin
  | Ext_Zvbb
  | Ext_Zvbc
  | Ext_Zvkb
  | Ext_Zvkg
  | Ext_Zvkned
  | Ext_Zvknha
  | Ext_Zvknhb
  | Ext_Zvksed
  | Ext_Zvksh
  | Ext_Zvkt
  | Ext_Zvkn
  | Ext_Zvknc
  | Ext_Zvkng
  | Ext_Zvks
  | Ext_Zvksc
  | Ext_Zvksg
  | Ext_Ssccptr
  | Ext_Sscofpmf
  | Ext_Sscounterenw
  | Ext_Ssnpm
  | Ext_Ssstateen
  | Ext_Sstc
  | Ext_Sstvala
  | Ext_Sstvecd
  | Ext_Ssu64xl
  | Ext_Svbare
  | Ext_Sv32
  | Ext_Sv39
  | Ext_Sv48
  | Ext_Sv57
  | Ext_Svade
  | Ext_Svadu
  | Ext_Svinval
  | Ext_Svnapot
  | Ext_Svpbmt
  | Ext_Svrsw60t59b
  | Ext_Svvptc
  | Ext_Smcntrpmf
  | Ext_Smmpm
  | Ext_Smnpm
  | Ext_Smstateen
  | Ext_Ssqosid
  | Ext_Sspm
  | Ext_Supm



datatype Privilege =   User | VirtualUser | Supervisor | VirtualSupervisor | Machine



datatype TrapCause  =   Interrupt " (InterruptType)" | Exception0 " (ExceptionType)"



datatype WaitReason =   WAIT_WFI | WAIT_WRS_STO | WAIT_WRS_NTO



record GlobalMisalignedExceptions  =
  
 GlobalMisalignedExceptions_load_store ::"  misaligned_exception option " 

     GlobalMisalignedExceptions_vector ::"  misaligned_exception option " 

     GlobalMisalignedExceptions_lrsc ::" misaligned_exception " 

     GlobalMisalignedExceptions_amo ::" misaligned_exception "  



datatype ExtContextPolicy =   ExtContext_Off | ExtContext_TwoState | ExtContext_FourState



datatype AmocasOddRegisterReservedBehavior =   AMOCAS_Fatal | AMOCAS_Illegal



datatype FcsrRmReservedBehavior =   Fcsr_RM_Fatal | Fcsr_RM_Illegal



datatype PmpWriteOnlyReservedBehavior =   PMP_Fatal | PMP_ClearPermissions



datatype XenvcfgCbieReservedBehavior =   Xenvcfg_Fatal | Xenvcfg_ClearPermissions



datatype XtvecModeReservedBehavior =   Xtvec_Fatal | Xtvec_Ignore



datatype RV32ZdinxOddRegisterReservedBehavior =   Zdinx_Fatal | Zdinx_Illegal



datatype IllegalVtypeReservedBehavior =
    IllegalVtype_SetVill | IllegalVtype_Illegal | IllegalVtype_Fatal



datatype OOBVstartReservedBehavior =   Vstart_Illegal | Vstart_Ignore



type_synonym exc_code  =" bitU list "


type_synonym ext_ptw  =" unit "


type_synonym ext_ptw_fail  =" unit "


type_synonym ext_ptw_error  =" unit "


type_synonym half  =" bitU list "


type_synonym word0  =" bitU list "


type_synonym instbits  =" bitU list "




datatype cregidx  =   Cregidx " ( bitU list)"



datatype regno  =   Regno " (int)"



type_synonym arch_xlen  =" bitU list "


type_synonym nom_priv_bits  =" bitU list "


type_synonym virt_mode_bit  =" bitU list "


datatype CSRAccessType =   CSRRead | CSRWrite | CSRReadWrite





datatype SWCheckCodes =   LANDING_PAD_FAULT



type_synonym tv_mode  =" bitU list "


datatype TrapVectorMode =   TV_Direct | TV_Vector | TV_Reserved



datatype xRET_type =   MRET | SRET



type_synonym ext_status  =" bitU list "


datatype ExtStatus =   Off | Initial | Clean | Dirty



type_synonym satp_mode  =" bitU list "


datatype SATPMode =   Bare | Sv32 | Sv39 | Sv48 | Sv57



type_synonym csrRW  =" bitU list "


type_synonym word_width  =" int "


type_synonym word_width_wide  =" int "




type_synonym level_range  =" int "


type_synonym pte_bits  =" bitU list "


type_synonym ppn_bits  =" bitU list "


type_synonym vpn_bits  =" bitU list "


datatype page_based_mem_type =   PBMT_PMA | PBMT_NC | PBMT_IO



type_synonym regtype  =" bitU list "


type_synonym Mstatus  =" bitU list "


type_synonym Seccfg  =" bitU list "


type_synonym MEnvcfg  =" bitU list "


type_synonym SEnvcfg  =" bitU list "


type_synonym Mtvec  =" bitU list "


type_synonym Mcause  =" bitU list "


type_synonym Counteren  =" bitU list "


type_synonym Counterin  =" bitU list "


type_synonym Sstatus  =" bitU list "


type_synonym Satp64  =" bitU list "


type_synonym Satp32  =" bitU list "


datatype FeatureEnabledResult =   FEATURE_ENABLED | FEATURE_ILLEGAL | FEATURE_VIRTUAL



type_synonym Minterrupts  =" bitU list "


type_synonym Medeleg  =" bitU list "


datatype XipReadType =   IncludePlatformInterrupts | ExcludePlatformInterrupts



type_synonym Sinterrupts  =" bitU list "


datatype 'a Ext_DataAddr_Check =   Ext_DataAddr_OK " (virtaddr)" | Ext_DataAddr_Error " ('a)"



type_synonym ext_fetch_addr_error  =" unit "


type_synonym ext_control_addr_error  =" unit "


type_synonym ext_data_addr_error  =" unit "


type_synonym bits_rm  =" bitU list "


type_synonym bits_fflags  =" bitU list "


type_synonym bits_BF16  =" bitU list "


type_synonym bits_H  =" bitU list "


type_synonym bits_S  =" bitU list "


type_synonym bits_D  =" bitU list "


type_synonym bits_W  =" bitU list "


type_synonym bits_WU  =" bitU list "


type_synonym bits_L  =" bitU list "


type_synonym bits_LU  =" bitU list "


type_synonym ext_exception  =" unit "


record sync_exception  =
  
 sync_exception_trap ::" ExceptionType " 

     sync_exception_excinfo ::"  ( bitU list)option " 

     sync_exception_ext_exception ::"  unit option "  



datatype PmpAddrMatchType =   OFF | TOR | NA4 | NAPOT



type_synonym Pmpcfg_ent  =" bitU list "


datatype pmpAddrMatch =   PMP_NoMatch | PMP_PartialMatch | PMP_Match



datatype register_value  =
    Regval_vector " ( register_value list)"
  | Regval_list " ( register_value list)"
  | Regval_option " ( register_value option)"
  | Regval_bool " (bool)"
  | Regval_int " (ii)"
  | Regval_real " (real)"
  | Regval_string " (string)"
  | Regval_Privilege " (Privilege)"
  | Regval_bitvector_1 " ( bitU list)"
  | Regval_bitvector_128 " ( bitU list)"
  | Regval_bitvector_192 " ( bitU list)"
  | Regval_bitvector_32 " ( bitU list)"
  | Regval_bitvector_320 " ( bitU list)"
  | Regval_bitvector_5 " ( bitU list)"
  | Regval_bitvector_64 " ( bitU list)"
  | Regval_bitvector_704 " ( bitU list)"
  | Regval_bitvector_8 " ( bitU list)"



record regstate  =
  
 sig_seip ::" bitU list " 

     sig_meip ::" bitU list " 

     pmpaddr_n ::" ( bitU list) list " 

     pmpcfg_n ::" ( bitU list) list " 

     mideleg ::" bitU list " 

     medeleg ::" bitU list " 

     mip ::" bitU list " 

     mie ::" bitU list " 

     tselect ::" bitU list " 

     stval ::" bitU list " 

     scause ::" bitU list " 

     sepc ::" bitU list " 

     sscratch ::" bitU list " 

     stvec ::" bitU list " 

     mconfigptr ::" bitU list " 

     mhartid ::" bitU list " 

     marchid ::" bitU list " 

     mimpid ::" bitU list " 

     mvendorid ::" bitU list " 

     minstret_increment ::" bool " 

     minstret ::" bitU list " 

     mtime ::" bitU list " 

     mcycle ::" bitU list " 

     mcountinhibit ::" bitU list " 

     mcounteren ::" bitU list " 

     scounteren ::" bitU list " 

     mscratch ::" bitU list " 

     mtval ::" bitU list " 

     mepc ::" bitU list " 

     mcause ::" bitU list " 

     mtvec ::" bitU list " 

     senvcfg ::" bitU list " 

     menvcfg ::" bitU list " 

     mseccfg ::" bitU list " 

     mstatus ::" bitU list " 

     misa ::" bitU list " 

     cur_inst ::" bitU list " 

     cur_privilege ::" Privilege " 

     x31 ::" bitU list " 

     x30 ::" bitU list " 

     x29 ::" bitU list " 

     x28 ::" bitU list " 

     x27 ::" bitU list " 

     x26 ::" bitU list " 

     x25 ::" bitU list " 

     x24 ::" bitU list " 

     x23 ::" bitU list " 

     x22 ::" bitU list " 

     x21 ::" bitU list " 

     x20 ::" bitU list " 

     x19 ::" bitU list " 

     x18 ::" bitU list " 

     x17 ::" bitU list " 

     x16 ::" bitU list " 

     x15 ::" bitU list " 

     x14 ::" bitU list " 

     x13 ::" bitU list " 

     x12 ::" bitU list " 

     x11 ::" bitU list " 

     x10 ::" bitU list " 

     x9 ::" bitU list " 

     x8 ::" bitU list " 

     x7 ::" bitU list " 

     x6 ::" bitU list " 

     x5 ::" bitU list " 

     x4 ::" bitU list " 

     x3 ::" bitU list " 

     x2 ::" bitU list " 

     x1 ::" bitU list " 

     nextPC ::" bitU list " 

     PC ::" bitU list " 

     rvfi_mem_data_present ::" bool " 

     rvfi_mem_data ::" bitU list " 

     rvfi_int_data_present ::" bool " 

     rvfi_int_data ::" bitU list " 

     rvfi_pc_data ::" bitU list " 

     rvfi_inst_data ::" bitU list " 

     rvfi_instruction ::" bitU list " 

     fp_rounding_global ::" bitU list "  



\<comment> \<open>\<open>val Privilege_of_regval : register_value -> (maybe Privilege)\<close>\<close>

fun Privilege_of_regval  :: \<open> register_value \<Rightarrow>(Privilege)option \<close>  where 
     \<open> Privilege_of_regval (Regval_Privilege (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: " Privilege "
|\<open> Privilege_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_Privilege : Privilege -> register_value\<close>\<close>

definition regval_of_Privilege  :: \<open> Privilege \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_Privilege v0 = ( Regval_Privilege v0 )\<close> 
  for  "v0"  :: " Privilege "


\<comment> \<open>\<open>val bitvector_1_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_1_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_1_of_regval (Regval_bitvector_1 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_1_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_1 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_1  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_1 v0 = ( Regval_bitvector_1 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_128_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_128_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_128_of_regval (Regval_bitvector_128 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_128_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_128 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_128  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_128 v0 = ( Regval_bitvector_128 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_192_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_192_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_192_of_regval (Regval_bitvector_192 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_192_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_192 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_192  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_192 v0 = ( Regval_bitvector_192 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_32_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_32_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_32_of_regval (Regval_bitvector_32 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_32_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_32 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_32  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_32 v0 = ( Regval_bitvector_32 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_320_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_320_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_320_of_regval (Regval_bitvector_320 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_320_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_320 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_320  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_320 v0 = ( Regval_bitvector_320 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_5_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_5_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_5_of_regval (Regval_bitvector_5 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_5_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_5 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_5  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_5 v0 = ( Regval_bitvector_5 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_64_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_64_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_64_of_regval (Regval_bitvector_64 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_64_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_64 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_64  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_64 v0 = ( Regval_bitvector_64 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_704_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_704_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_704_of_regval (Regval_bitvector_704 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_704_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_704 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_704  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_704 v0 = ( Regval_bitvector_704 v0 )\<close> 
  for  "v0"  :: "(bitU)list "


\<comment> \<open>\<open>val bitvector_8_of_regval : register_value -> (maybe (list bitU))\<close>\<close>

fun bitvector_8_of_regval  :: \<open> register_value \<Rightarrow>((bitU)list)option \<close>  where 
     \<open> bitvector_8_of_regval (Regval_bitvector_8 (v0)) = ( Some v0 )\<close> 
  for  "v0"  :: "(bitU)list "
|\<open> bitvector_8_of_regval _ = ( None )\<close>


\<comment> \<open>\<open>val regval_of_bitvector_8 : list bitU -> register_value\<close>\<close>

definition regval_of_bitvector_8  :: \<open>(bitU)list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_bitvector_8 v0 = ( Regval_bitvector_8 v0 )\<close> 
  for  "v0"  :: "(bitU)list "




\<comment> \<open>\<open>val bool_of_register_value : register_value -> maybe bool\<close>\<close>
fun bool_of_register_value  :: \<open> register_value \<Rightarrow>(bool)option \<close>  where 
     \<open> bool_of_register_value (Regval_bool v) = ( Some v )\<close> 
  for  "v"  :: " bool "
|\<open> bool_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_bool : bool -> register_value\<close>\<close>
definition register_value_of_bool  :: \<open> bool \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_bool v = ( Regval_bool v )\<close> 
  for  "v"  :: " bool "

\<comment> \<open>\<open>val int_of_register_value : register_value -> maybe integer\<close>\<close>
fun int_of_register_value  :: \<open> register_value \<Rightarrow>(int)option \<close>  where 
     \<open> int_of_register_value (Regval_int v) = ( Some v )\<close> 
  for  "v"  :: " int "
|\<open> int_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_int : integer -> register_value\<close>\<close>
definition register_value_of_int  :: \<open> int \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_int v = ( Regval_int v )\<close> 
  for  "v"  :: " int "

\<comment> \<open>\<open>val real_of_register_value : register_value -> maybe real\<close>\<close>
fun real_of_register_value  :: \<open> register_value \<Rightarrow>(real)option \<close>  where 
     \<open> real_of_register_value (Regval_real v) = ( Some v )\<close> 
  for  "v"  :: " real "
|\<open> real_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_real : real -> register_value\<close>\<close>
definition register_value_of_real  :: \<open> real \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_real v = ( Regval_real v )\<close> 
  for  "v"  :: " real "

\<comment> \<open>\<open>val string_of_register_value : register_value -> maybe string\<close>\<close>
fun string_of_register_value  :: \<open> register_value \<Rightarrow>(string)option \<close>  where 
     \<open> string_of_register_value (Regval_string v) = ( Some v )\<close> 
  for  "v"  :: " string "
|\<open> string_of_register_value _ = ( None )\<close>

\<comment> \<open>\<open>val register_value_of_string : string -> register_value\<close>\<close>
definition register_value_of_string  :: \<open> string \<Rightarrow> register_value \<close>  where 
     \<open> register_value_of_string v = ( Regval_string v )\<close> 
  for  "v"  :: " string "


definition instance_Sail2_values_Register_Value_Rv64d_types_register_value_dict  :: \<open>(register_value)Register_Value_class \<close>  where 
     \<open> instance_Sail2_values_Register_Value_Rv64d_types_register_value_dict = ((|

  bool_of_regval_method = bool_of_register_value,

  regval_of_bool_method = register_value_of_bool,

  int_of_regval_method = int_of_register_value,

  regval_of_int_method = register_value_of_int,

  real_of_regval_method = real_of_register_value,

  regval_of_real_method = register_value_of_real,

  string_of_regval_method = string_of_register_value,

  regval_of_string_method = register_value_of_string |) )\<close>

\<comment> \<open>\<open>val vector_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (list 'a)\<close>\<close>
fun vector_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a list)option \<close>  where 
     \<open> vector_of_regval of_regval1 (Regval_vector v) = ( just_list (List.map of_regval1 v))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)list "
|\<open> vector_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_vector : forall 'a. ('a -> register_value) -> list 'a -> register_value\<close>\<close>
definition regval_of_vector  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_vector regval_of1 xs = ( Regval_vector (List.map regval_of1 xs))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "xs"  :: " 'a list "


\<comment> \<open>\<open>val list_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (list 'a)\<close>\<close>
fun list_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a list)option \<close>  where 
     \<open> list_of_regval of_regval1 (Regval_list v) = ( just_list (List.map of_regval1 v))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)list "
|\<open> list_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_list : forall 'a. ('a -> register_value) -> list 'a -> register_value\<close>\<close>
definition regval_of_list  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a list \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_list regval_of1 xs = ( Regval_list (List.map regval_of1 xs))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "xs"  :: " 'a list "


\<comment> \<open>\<open>val option_of_regval : forall 'a. (register_value -> maybe 'a) -> register_value -> maybe (maybe 'a)\<close>\<close>
fun option_of_regval  :: \<open>(register_value \<Rightarrow> 'a option)\<Rightarrow> register_value \<Rightarrow>('a option)option \<close>  where 
     \<open> option_of_regval of_regval1 (Regval_option v) = ( Some (Option.bind v of_regval1))\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option " 
  and  "v"  :: "(register_value)option "
|\<open> option_of_regval of_regval1 _ = ( None )\<close> 
  for  "of_regval1"  :: " register_value \<Rightarrow> 'a option "


\<comment> \<open>\<open>val regval_of_option : forall 'a. ('a -> register_value) -> maybe 'a -> register_value\<close>\<close>
definition regval_of_option  :: \<open>('a \<Rightarrow> register_value)\<Rightarrow> 'a option \<Rightarrow> register_value \<close>  where 
     \<open> regval_of_option regval_of1 v = ( Regval_option (map_option regval_of1 v))\<close> 
  for  "regval_of1"  :: " 'a \<Rightarrow> register_value " 
  and  "v"  :: " 'a option "



definition pmpaddr_n_ref  :: \<open>((regstate),(register_value),(((bitU)list)list))register_ref \<close>  where 
     \<open> pmpaddr_n_ref = ( (|
  name = (''pmpaddr_n''),
  read_from = ((\<lambda> s . (pmpaddr_n   s))),
  write_to = ((\<lambda> v s .  (( s (| pmpaddr_n := v |))))),
  of_regval = ((\<lambda> v .  vector_of_regval ((\<lambda> v .  bitvector_64_of_regval v)) v)),
  regval_of = ((\<lambda> v .  regval_of_vector ((\<lambda> v .  regval_of_bitvector_64 v)) v)) |) )\<close>


definition pmpcfg_n_ref  :: \<open>((regstate),(register_value),(((bitU)list)list))register_ref \<close>  where 
     \<open> pmpcfg_n_ref = ( (|
  name = (''pmpcfg_n''),
  read_from = ((\<lambda> s . (pmpcfg_n   s))),
  write_to = ((\<lambda> v s .  (( s (| pmpcfg_n := v |))))),
  of_regval = ((\<lambda> v .  vector_of_regval ((\<lambda> v .  bitvector_8_of_regval v)) v)),
  regval_of = ((\<lambda> v .  regval_of_vector ((\<lambda> v .  regval_of_bitvector_8 v)) v)) |) )\<close>


definition sig_seip_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> sig_seip_ref = ( (|
  name = (''sig_seip''),
  read_from = ((\<lambda> s . (sig_seip   s))),
  write_to = ((\<lambda> v s .  (( s (| sig_seip := v |))))),
  of_regval = ((\<lambda> v .  bitvector_1_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_1 v)) |) )\<close>


definition sig_meip_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> sig_meip_ref = ( (|
  name = (''sig_meip''),
  read_from = ((\<lambda> s . (sig_meip   s))),
  write_to = ((\<lambda> v s .  (( s (| sig_meip := v |))))),
  of_regval = ((\<lambda> v .  bitvector_1_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_1 v)) |) )\<close>


definition mideleg_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mideleg_ref = ( (|
  name = (''mideleg''),
  read_from = ((\<lambda> s . (mideleg   s))),
  write_to = ((\<lambda> v s .  (( s (| mideleg := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition medeleg_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> medeleg_ref = ( (|
  name = (''medeleg''),
  read_from = ((\<lambda> s . (medeleg   s))),
  write_to = ((\<lambda> v s .  (( s (| medeleg := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mip_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mip_ref = ( (|
  name = (''mip''),
  read_from = ((\<lambda> s . (mip   s))),
  write_to = ((\<lambda> v s .  (( s (| mip := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mie_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mie_ref = ( (|
  name = (''mie''),
  read_from = ((\<lambda> s . (mie   s))),
  write_to = ((\<lambda> v s .  (( s (| mie := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition tselect_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> tselect_ref = ( (|
  name = (''tselect''),
  read_from = ((\<lambda> s . (tselect   s))),
  write_to = ((\<lambda> v s .  (( s (| tselect := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition stval_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> stval_ref = ( (|
  name = (''stval''),
  read_from = ((\<lambda> s . (stval   s))),
  write_to = ((\<lambda> v s .  (( s (| stval := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition scause_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> scause_ref = ( (|
  name = (''scause''),
  read_from = ((\<lambda> s . (scause   s))),
  write_to = ((\<lambda> v s .  (( s (| scause := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition sepc_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> sepc_ref = ( (|
  name = (''sepc''),
  read_from = ((\<lambda> s . (sepc   s))),
  write_to = ((\<lambda> v s .  (( s (| sepc := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition sscratch_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> sscratch_ref = ( (|
  name = (''sscratch''),
  read_from = ((\<lambda> s . (sscratch   s))),
  write_to = ((\<lambda> v s .  (( s (| sscratch := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition stvec_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> stvec_ref = ( (|
  name = (''stvec''),
  read_from = ((\<lambda> s . (stvec   s))),
  write_to = ((\<lambda> v s .  (( s (| stvec := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mconfigptr_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mconfigptr_ref = ( (|
  name = (''mconfigptr''),
  read_from = ((\<lambda> s . (mconfigptr   s))),
  write_to = ((\<lambda> v s .  (( s (| mconfigptr := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mhartid_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mhartid_ref = ( (|
  name = (''mhartid''),
  read_from = ((\<lambda> s . (mhartid   s))),
  write_to = ((\<lambda> v s .  (( s (| mhartid := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition marchid_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> marchid_ref = ( (|
  name = (''marchid''),
  read_from = ((\<lambda> s . (marchid   s))),
  write_to = ((\<lambda> v s .  (( s (| marchid := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mimpid_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mimpid_ref = ( (|
  name = (''mimpid''),
  read_from = ((\<lambda> s . (mimpid   s))),
  write_to = ((\<lambda> v s .  (( s (| mimpid := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mvendorid_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mvendorid_ref = ( (|
  name = (''mvendorid''),
  read_from = ((\<lambda> s . (mvendorid   s))),
  write_to = ((\<lambda> v s .  (( s (| mvendorid := v |))))),
  of_regval = ((\<lambda> v .  bitvector_32_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_32 v)) |) )\<close>


definition minstret_increment_ref  :: \<open>((regstate),(register_value),(bool))register_ref \<close>  where 
     \<open> minstret_increment_ref = ( (|
  name = (''minstret_increment''),
  read_from = ((\<lambda> s . (minstret_increment   s))),
  write_to = ((\<lambda> v s .  (( s (| minstret_increment := v |))))),
  of_regval = ((\<lambda> v .  bool_of_register_value v)),
  regval_of = ((\<lambda> v .  register_value_of_bool v)) |) )\<close>


definition minstret_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> minstret_ref = ( (|
  name = (''minstret''),
  read_from = ((\<lambda> s . (minstret   s))),
  write_to = ((\<lambda> v s .  (( s (| minstret := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mtime_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mtime_ref = ( (|
  name = (''mtime''),
  read_from = ((\<lambda> s . (mtime   s))),
  write_to = ((\<lambda> v s .  (( s (| mtime := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mcycle_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mcycle_ref = ( (|
  name = (''mcycle''),
  read_from = ((\<lambda> s . (mcycle   s))),
  write_to = ((\<lambda> v s .  (( s (| mcycle := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mcountinhibit_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mcountinhibit_ref = ( (|
  name = (''mcountinhibit''),
  read_from = ((\<lambda> s . (mcountinhibit   s))),
  write_to = ((\<lambda> v s .  (( s (| mcountinhibit := v |))))),
  of_regval = ((\<lambda> v .  bitvector_32_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_32 v)) |) )\<close>


definition mcounteren_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mcounteren_ref = ( (|
  name = (''mcounteren''),
  read_from = ((\<lambda> s . (mcounteren   s))),
  write_to = ((\<lambda> v s .  (( s (| mcounteren := v |))))),
  of_regval = ((\<lambda> v .  bitvector_32_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_32 v)) |) )\<close>


definition scounteren_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> scounteren_ref = ( (|
  name = (''scounteren''),
  read_from = ((\<lambda> s . (scounteren   s))),
  write_to = ((\<lambda> v s .  (( s (| scounteren := v |))))),
  of_regval = ((\<lambda> v .  bitvector_32_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_32 v)) |) )\<close>


definition mscratch_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mscratch_ref = ( (|
  name = (''mscratch''),
  read_from = ((\<lambda> s . (mscratch   s))),
  write_to = ((\<lambda> v s .  (( s (| mscratch := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mtval_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mtval_ref = ( (|
  name = (''mtval''),
  read_from = ((\<lambda> s . (mtval   s))),
  write_to = ((\<lambda> v s .  (( s (| mtval := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mepc_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mepc_ref = ( (|
  name = (''mepc''),
  read_from = ((\<lambda> s . (mepc   s))),
  write_to = ((\<lambda> v s .  (( s (| mepc := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mcause_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mcause_ref = ( (|
  name = (''mcause''),
  read_from = ((\<lambda> s . (mcause   s))),
  write_to = ((\<lambda> v s .  (( s (| mcause := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mtvec_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mtvec_ref = ( (|
  name = (''mtvec''),
  read_from = ((\<lambda> s . (mtvec   s))),
  write_to = ((\<lambda> v s .  (( s (| mtvec := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition senvcfg_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> senvcfg_ref = ( (|
  name = (''senvcfg''),
  read_from = ((\<lambda> s . (senvcfg   s))),
  write_to = ((\<lambda> v s .  (( s (| senvcfg := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition menvcfg_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> menvcfg_ref = ( (|
  name = (''menvcfg''),
  read_from = ((\<lambda> s . (menvcfg   s))),
  write_to = ((\<lambda> v s .  (( s (| menvcfg := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mseccfg_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mseccfg_ref = ( (|
  name = (''mseccfg''),
  read_from = ((\<lambda> s . (mseccfg   s))),
  write_to = ((\<lambda> v s .  (( s (| mseccfg := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition mstatus_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> mstatus_ref = ( (|
  name = (''mstatus''),
  read_from = ((\<lambda> s . (mstatus   s))),
  write_to = ((\<lambda> v s .  (( s (| mstatus := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition cur_inst_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> cur_inst_ref = ( (|
  name = (''cur_inst''),
  read_from = ((\<lambda> s . (cur_inst   s))),
  write_to = ((\<lambda> v s .  (( s (| cur_inst := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition cur_privilege_ref  :: \<open>((regstate),(register_value),(Privilege))register_ref \<close>  where 
     \<open> cur_privilege_ref = ( (|
  name = (''cur_privilege''),
  read_from = ((\<lambda> s . (cur_privilege   s))),
  write_to = ((\<lambda> v s .  (( s (| cur_privilege := v |))))),
  of_regval = ((\<lambda> v .  Privilege_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_Privilege v)) |) )\<close>


definition x31_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x31_ref = ( (|
  name = (''x31''),
  read_from = ((\<lambda> s . (x31   s))),
  write_to = ((\<lambda> v s .  (( s (| x31 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x30_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x30_ref = ( (|
  name = (''x30''),
  read_from = ((\<lambda> s . (x30   s))),
  write_to = ((\<lambda> v s .  (( s (| x30 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x29_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x29_ref = ( (|
  name = (''x29''),
  read_from = ((\<lambda> s . (x29   s))),
  write_to = ((\<lambda> v s .  (( s (| x29 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x28_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x28_ref = ( (|
  name = (''x28''),
  read_from = ((\<lambda> s . (x28   s))),
  write_to = ((\<lambda> v s .  (( s (| x28 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x27_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x27_ref = ( (|
  name = (''x27''),
  read_from = ((\<lambda> s . (x27   s))),
  write_to = ((\<lambda> v s .  (( s (| x27 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x26_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x26_ref = ( (|
  name = (''x26''),
  read_from = ((\<lambda> s . (x26   s))),
  write_to = ((\<lambda> v s .  (( s (| x26 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x25_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x25_ref = ( (|
  name = (''x25''),
  read_from = ((\<lambda> s . (x25   s))),
  write_to = ((\<lambda> v s .  (( s (| x25 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x24_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x24_ref = ( (|
  name = (''x24''),
  read_from = ((\<lambda> s . (x24   s))),
  write_to = ((\<lambda> v s .  (( s (| x24 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x23_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x23_ref = ( (|
  name = (''x23''),
  read_from = ((\<lambda> s . (x23   s))),
  write_to = ((\<lambda> v s .  (( s (| x23 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x22_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x22_ref = ( (|
  name = (''x22''),
  read_from = ((\<lambda> s . (x22   s))),
  write_to = ((\<lambda> v s .  (( s (| x22 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x21_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x21_ref = ( (|
  name = (''x21''),
  read_from = ((\<lambda> s . (x21   s))),
  write_to = ((\<lambda> v s .  (( s (| x21 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x20_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x20_ref = ( (|
  name = (''x20''),
  read_from = ((\<lambda> s . (x20   s))),
  write_to = ((\<lambda> v s .  (( s (| x20 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x19_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x19_ref = ( (|
  name = (''x19''),
  read_from = ((\<lambda> s . (x19   s))),
  write_to = ((\<lambda> v s .  (( s (| x19 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x18_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x18_ref = ( (|
  name = (''x18''),
  read_from = ((\<lambda> s . (x18   s))),
  write_to = ((\<lambda> v s .  (( s (| x18 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x17_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x17_ref = ( (|
  name = (''x17''),
  read_from = ((\<lambda> s . (x17   s))),
  write_to = ((\<lambda> v s .  (( s (| x17 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x16_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x16_ref = ( (|
  name = (''x16''),
  read_from = ((\<lambda> s . (x16   s))),
  write_to = ((\<lambda> v s .  (( s (| x16 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x15_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x15_ref = ( (|
  name = (''x15''),
  read_from = ((\<lambda> s . (x15   s))),
  write_to = ((\<lambda> v s .  (( s (| x15 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x14_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x14_ref = ( (|
  name = (''x14''),
  read_from = ((\<lambda> s . (x14   s))),
  write_to = ((\<lambda> v s .  (( s (| x14 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x13_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x13_ref = ( (|
  name = (''x13''),
  read_from = ((\<lambda> s . (x13   s))),
  write_to = ((\<lambda> v s .  (( s (| x13 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x12_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x12_ref = ( (|
  name = (''x12''),
  read_from = ((\<lambda> s . (x12   s))),
  write_to = ((\<lambda> v s .  (( s (| x12 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x11_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x11_ref = ( (|
  name = (''x11''),
  read_from = ((\<lambda> s . (x11   s))),
  write_to = ((\<lambda> v s .  (( s (| x11 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x10_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x10_ref = ( (|
  name = (''x10''),
  read_from = ((\<lambda> s . (x10   s))),
  write_to = ((\<lambda> v s .  (( s (| x10 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x9_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x9_ref = ( (|
  name = (''x9''),
  read_from = ((\<lambda> s . (x9   s))),
  write_to = ((\<lambda> v s .  (( s (| x9 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x8_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x8_ref = ( (|
  name = (''x8''),
  read_from = ((\<lambda> s . (x8   s))),
  write_to = ((\<lambda> v s .  (( s (| x8 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x7_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x7_ref = ( (|
  name = (''x7''),
  read_from = ((\<lambda> s . (x7   s))),
  write_to = ((\<lambda> v s .  (( s (| x7 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x6_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x6_ref = ( (|
  name = (''x6''),
  read_from = ((\<lambda> s . (x6   s))),
  write_to = ((\<lambda> v s .  (( s (| x6 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x5_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x5_ref = ( (|
  name = (''x5''),
  read_from = ((\<lambda> s . (x5   s))),
  write_to = ((\<lambda> v s .  (( s (| x5 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x4_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x4_ref = ( (|
  name = (''x4''),
  read_from = ((\<lambda> s . (x4   s))),
  write_to = ((\<lambda> v s .  (( s (| x4 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x3_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x3_ref = ( (|
  name = (''x3''),
  read_from = ((\<lambda> s . (x3   s))),
  write_to = ((\<lambda> v s .  (( s (| x3 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x2_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x2_ref = ( (|
  name = (''x2''),
  read_from = ((\<lambda> s . (x2   s))),
  write_to = ((\<lambda> v s .  (( s (| x2 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition x1_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> x1_ref = ( (|
  name = (''x1''),
  read_from = ((\<lambda> s . (x1   s))),
  write_to = ((\<lambda> v s .  (( s (| x1 := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition nextPC_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> nextPC_ref = ( (|
  name = (''nextPC''),
  read_from = ((\<lambda> s . (nextPC   s))),
  write_to = ((\<lambda> v s .  (( s (| nextPC := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition PC_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> PC_ref = ( (|
  name = (''PC''),
  read_from = ((\<lambda> s . (PC   s))),
  write_to = ((\<lambda> v s .  (( s (| PC := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition misa_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> misa_ref = ( (|
  name = (''misa''),
  read_from = ((\<lambda> s . (misa   s))),
  write_to = ((\<lambda> v s .  (( s (| misa := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition rvfi_mem_data_present_ref  :: \<open>((regstate),(register_value),(bool))register_ref \<close>  where 
     \<open> rvfi_mem_data_present_ref = ( (|
  name = (''rvfi_mem_data_present''),
  read_from = ((\<lambda> s . (rvfi_mem_data_present   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_mem_data_present := v |))))),
  of_regval = ((\<lambda> v .  bool_of_register_value v)),
  regval_of = ((\<lambda> v .  register_value_of_bool v)) |) )\<close>


definition rvfi_mem_data_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> rvfi_mem_data_ref = ( (|
  name = (''rvfi_mem_data''),
  read_from = ((\<lambda> s . (rvfi_mem_data   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_mem_data := v |))))),
  of_regval = ((\<lambda> v .  bitvector_704_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_704 v)) |) )\<close>


definition rvfi_int_data_present_ref  :: \<open>((regstate),(register_value),(bool))register_ref \<close>  where 
     \<open> rvfi_int_data_present_ref = ( (|
  name = (''rvfi_int_data_present''),
  read_from = ((\<lambda> s . (rvfi_int_data_present   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_int_data_present := v |))))),
  of_regval = ((\<lambda> v .  bool_of_register_value v)),
  regval_of = ((\<lambda> v .  register_value_of_bool v)) |) )\<close>


definition rvfi_int_data_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> rvfi_int_data_ref = ( (|
  name = (''rvfi_int_data''),
  read_from = ((\<lambda> s . (rvfi_int_data   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_int_data := v |))))),
  of_regval = ((\<lambda> v .  bitvector_320_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_320 v)) |) )\<close>


definition rvfi_pc_data_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> rvfi_pc_data_ref = ( (|
  name = (''rvfi_pc_data''),
  read_from = ((\<lambda> s . (rvfi_pc_data   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_pc_data := v |))))),
  of_regval = ((\<lambda> v .  bitvector_128_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_128 v)) |) )\<close>


definition rvfi_inst_data_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> rvfi_inst_data_ref = ( (|
  name = (''rvfi_inst_data''),
  read_from = ((\<lambda> s . (rvfi_inst_data   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_inst_data := v |))))),
  of_regval = ((\<lambda> v .  bitvector_192_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_192 v)) |) )\<close>


definition rvfi_instruction_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> rvfi_instruction_ref = ( (|
  name = (''rvfi_instruction''),
  read_from = ((\<lambda> s . (rvfi_instruction   s))),
  write_to = ((\<lambda> v s .  (( s (| rvfi_instruction := v |))))),
  of_regval = ((\<lambda> v .  bitvector_64_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_64 v)) |) )\<close>


definition fp_rounding_global_ref  :: \<open>((regstate),(register_value),((bitU)list))register_ref \<close>  where 
     \<open> fp_rounding_global_ref = ( (|
  name = (''fp_rounding_global''),
  read_from = ((\<lambda> s . (fp_rounding_global   s))),
  write_to = ((\<lambda> v s .  (( s (| fp_rounding_global := v |))))),
  of_regval = ((\<lambda> v .  bitvector_5_of_regval v)),
  regval_of = ((\<lambda> v .  regval_of_bitvector_5 v)) |) )\<close>


\<comment> \<open>\<open>val registers : list (string * register_ops regstate register_value)\<close>\<close>
definition registers  :: \<open>(string*((register_value \<Rightarrow> bool)*(regstate \<Rightarrow> register_value)*(register_value \<Rightarrow> regstate \<Rightarrow>(regstate)option)))list \<close>  where 
     \<open> registers = ( [
    ((''pmpaddr_n''), register_ops_of pmpaddr_n_ref),
    ((''pmpcfg_n''), register_ops_of pmpcfg_n_ref),
    ((''sig_seip''), register_ops_of sig_seip_ref),
    ((''sig_meip''), register_ops_of sig_meip_ref),
    ((''mideleg''), register_ops_of mideleg_ref),
    ((''medeleg''), register_ops_of medeleg_ref),
    ((''mip''), register_ops_of mip_ref),
    ((''mie''), register_ops_of mie_ref),
    ((''tselect''), register_ops_of tselect_ref),
    ((''stval''), register_ops_of stval_ref),
    ((''scause''), register_ops_of scause_ref),
    ((''sepc''), register_ops_of sepc_ref),
    ((''sscratch''), register_ops_of sscratch_ref),
    ((''stvec''), register_ops_of stvec_ref),
    ((''mconfigptr''), register_ops_of mconfigptr_ref),
    ((''mhartid''), register_ops_of mhartid_ref),
    ((''marchid''), register_ops_of marchid_ref),
    ((''mimpid''), register_ops_of mimpid_ref),
    ((''mvendorid''), register_ops_of mvendorid_ref),
    ((''minstret_increment''), register_ops_of minstret_increment_ref),
    ((''minstret''), register_ops_of minstret_ref),
    ((''mtime''), register_ops_of mtime_ref),
    ((''mcycle''), register_ops_of mcycle_ref),
    ((''mcountinhibit''), register_ops_of mcountinhibit_ref),
    ((''mcounteren''), register_ops_of mcounteren_ref),
    ((''scounteren''), register_ops_of scounteren_ref),
    ((''mscratch''), register_ops_of mscratch_ref),
    ((''mtval''), register_ops_of mtval_ref),
    ((''mepc''), register_ops_of mepc_ref),
    ((''mcause''), register_ops_of mcause_ref),
    ((''mtvec''), register_ops_of mtvec_ref),
    ((''senvcfg''), register_ops_of senvcfg_ref),
    ((''menvcfg''), register_ops_of menvcfg_ref),
    ((''mseccfg''), register_ops_of mseccfg_ref),
    ((''mstatus''), register_ops_of mstatus_ref),
    ((''cur_inst''), register_ops_of cur_inst_ref),
    ((''cur_privilege''), register_ops_of cur_privilege_ref),
    ((''x31''), register_ops_of x31_ref),
    ((''x30''), register_ops_of x30_ref),
    ((''x29''), register_ops_of x29_ref),
    ((''x28''), register_ops_of x28_ref),
    ((''x27''), register_ops_of x27_ref),
    ((''x26''), register_ops_of x26_ref),
    ((''x25''), register_ops_of x25_ref),
    ((''x24''), register_ops_of x24_ref),
    ((''x23''), register_ops_of x23_ref),
    ((''x22''), register_ops_of x22_ref),
    ((''x21''), register_ops_of x21_ref),
    ((''x20''), register_ops_of x20_ref),
    ((''x19''), register_ops_of x19_ref),
    ((''x18''), register_ops_of x18_ref),
    ((''x17''), register_ops_of x17_ref),
    ((''x16''), register_ops_of x16_ref),
    ((''x15''), register_ops_of x15_ref),
    ((''x14''), register_ops_of x14_ref),
    ((''x13''), register_ops_of x13_ref),
    ((''x12''), register_ops_of x12_ref),
    ((''x11''), register_ops_of x11_ref),
    ((''x10''), register_ops_of x10_ref),
    ((''x9''), register_ops_of x9_ref),
    ((''x8''), register_ops_of x8_ref),
    ((''x7''), register_ops_of x7_ref),
    ((''x6''), register_ops_of x6_ref),
    ((''x5''), register_ops_of x5_ref),
    ((''x4''), register_ops_of x4_ref),
    ((''x3''), register_ops_of x3_ref),
    ((''x2''), register_ops_of x2_ref),
    ((''x1''), register_ops_of x1_ref),
    ((''nextPC''), register_ops_of nextPC_ref),
    ((''PC''), register_ops_of PC_ref),
    ((''misa''), register_ops_of misa_ref),
    ((''rvfi_mem_data_present''), register_ops_of rvfi_mem_data_present_ref),
    ((''rvfi_mem_data''), register_ops_of rvfi_mem_data_ref),
    ((''rvfi_int_data_present''), register_ops_of rvfi_int_data_present_ref),
    ((''rvfi_int_data''), register_ops_of rvfi_int_data_ref),
    ((''rvfi_pc_data''), register_ops_of rvfi_pc_data_ref),
    ((''rvfi_inst_data''), register_ops_of rvfi_inst_data_ref),
    ((''rvfi_instruction''), register_ops_of rvfi_instruction_ref),
    ((''fp_rounding_global''), register_ops_of fp_rounding_global_ref)
  ])\<close>


definition register_accessors  :: \<open>(string \<Rightarrow> regstate \<Rightarrow>(register_value)option)*(string \<Rightarrow> register_value \<Rightarrow> regstate \<Rightarrow>(regstate)option)\<close>  where 
     \<open> register_accessors = ( mk_accessors ((\<lambda> nm .  Map.map_of registers nm)))\<close>


\<comment> \<open>\<open>val get_regval : string -> regstate -> maybe register_value\<close>\<close>
definition get_regval  :: \<open> string \<Rightarrow> regstate \<Rightarrow>(register_value)option \<close>  where 
     \<open> get_regval = ( fst register_accessors )\<close>


\<comment> \<open>\<open>val set_regval : string -> register_value -> regstate -> maybe regstate\<close>\<close>
definition set_regval  :: \<open> string \<Rightarrow> register_value \<Rightarrow> regstate \<Rightarrow>(regstate)option \<close>  where 
     \<open> set_regval = ( snd register_accessors )\<close>




type_synonym( 'a, 'r) MR =" (unit, barrier_kind0, unit, unit, ( bitU list), unit, unit, unit, unit, RISCV_strong_access, register_value, regstate, 'a, 'r, exception) base_monadR "
type_synonym 'a M =" (unit, barrier_kind0, unit, unit, ( bitU list), unit, unit, unit, unit, RISCV_strong_access, register_value, regstate, 'a, exception) base_monad "
end
