chapter \<open>Generated by Lem from \<open>/tmp/sesbi-full-official-isabelle/20260701T091640Z-2/model/rv64d.lem\<close>.\<close>

theory "Rv64dAuxiliary" 

imports
  Main
  "Rv64d_types"
  "LEM.Lem_pervasives_extra"
  "Sail.Sail2_instr_kinds"
  "Sail.Sail2_values"
  "Sail.Sail2_operators_bitlists"
  "Sail.Sail2_concurrency_interface"
  "Sail.Sail2_monadic_combinators"
  "Sail.Sail2_undefined_concurrency_interface"
  "Sail.Sail2_string"
  "Sail.Sail2_concurrency_interface_bitlists"
  "Riscv_extras_fdext"
  "Riscv_extras"
  "Rv64d"

begin 


\<comment> \<open>\<open>**************************************************\<close>\<close>
\<comment> \<open>\<open>                                                  \<close>\<close>
\<comment> \<open>\<open> Termination Proofs                               \<close>\<close>
\<comment> \<open>\<open>                                                  \<close>\<close>
\<comment> \<open>\<open>**************************************************\<close>\<close>

termination n_leading_spaces0 by lexicographic_order

termination rec_hartSupports by lexicographic_order

termination rec_currentlyEnabled by lexicographic_order



end
